esphome:
  name: eh_dor_sur_ac
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

logger:
  level: DEBUG

remote_receiver:
  id: rcvr
  pin:
    number: D5
    inverted: True
    mode: INPUT_PULLUP
  tolerance: 45%
  dump: raw

remote_transmitter:
  carrier_duty_percent: 50%
  pin: D6

climate:
  - platform: tcl112
    sensor: temp_sur
    name: 'AC Dormitorio Sur'
    supports_heat: True
    supports_cool: True
    receiver_id: rcvr

switch:
  - platform: restart
    name: "Dormitorio Sur Ac Restart"

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO4
    temperature:
      id: temp_sur
      name: Temperatura Dormitorio Sur
    humidity:
      name: Humedad Dormitorio Sur
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Dormitorio Sur AC Status"