substitutions:
  switch_number: '1'

esphome:
  board: nodemcu
  name: eh_smart_plug_${switch_number}
  platform: ESP8266

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:


# Enable Home Assistant API
api:
ota:

switch:
  - platform: gpio
    pin:
      number: D1
      inverted: true
    name: Smart Switch ${switch_number}