esphome:
  name: eh_captive
  platform: ESP8266
  board: nodemcu

logger:
  level: VERBOSE

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  ap:
    ssid: "ESP Hotspot"
    password: "12345678"

captive_portal:

web_server:

output:
  - platform: esp8266_pwm
    pin: D4
    frequency: 1000 Hz
    id: pwm_output

# Example usage in a light
light:
  - platform: monochromatic
    output: pwm_output
    name: "ESP Light"
