esphome:
  name: eh-camera-${cam_number}
  platform: ESP32
  board: nodemcu-32s
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings

  name: Camera ESP32 ${cam_number}
  resolution: 1280x1024
  max_framerate: 10Hz
  jpeg_quality: 20

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_led

light:
  - platform: binary
    output: gpio_led
    name: Camera ESP32 ${cam_number} Light

button:
  - platform: restart
    name: Camera ESP32 ${cam_number} Restart
