# Use a single PIN connected to the data pin of a TSOP receiver
# see: https://github.com/esphome/esphome/discussions/2078

remote_receiver:
  - id: ir_hack_rx
    pin:
      number: ${pin_number}
      inverted: True
      mode: OUTPUT_OPEN_DRAIN
      allow_other_uses: True
    tolerance: 45%

remote_transmitter:
  - id: ir_hack_tx
    carrier_duty_percent: 100%
    pin:
      number: ${pin_number}
      inverted: true
      mode: OUTPUT_OPEN_DRAIN
      allow_other_uses: True