sensor:
  - platform: dht
    model: AUTO_DETECT
    pin: ${pin}
    temperature:
      id: dht_temperature
      name: "Temperatura ${name}"
    humidity:
      name: "Humedad ${name}"
    update_interval: 60s