external_components:
  - source: github://glmnet/esphome-components
    components: [arduino_port_expander]

i2c:

arduino_port_expander:
  id: ape

output:
  - platform: gpio
    id: ape_relay_1
    inverted: true
    pin:
      arduino_port_expander: ape
      number: 7
  - platform: gpio
    id: ape_relay_2
    inverted: true
    pin:
      arduino_port_expander: ape
      number: 6
  - platform: gpio
    id: ape_relay_3
    inverted: true
    pin:
      arduino_port_expander: ape
      number: 5
  - platform: gpio
    id: ape_relay_4
    inverted: true
    pin:
      arduino_port_expander: ape
      number: 4
