i2c:
  id: i2c_component

sensor:
  - platform: bmp280_i2c
    address: 0x76
    update_interval: 60s
    temperature:
      id: bmp280_temperature
      name: "Temperatura ${name}"
      oversampling: 1x
    pressure:
      name: "Presion ${name}"
      oversampling: 1x