esphome:
  name: "${device_name}"
  platformio_options:
    upload_speed: 921600

api:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

ota:
  - platform: esphome

sensor:
  - platform: uptime
    name: ${friendly_name} uptime

button:
  - platform: restart
    name: ${friendly_name} restart

logger:

web_server:
  js_url: https://attilafarago.hu/smarthome/esphome_web_server/www.js
  auth:
    username: glm
    password: dontdamage
