substitutions:
  device_name: eh-cocina-ac
  friendly_name: Cocina AC

packages:
  board: !include .pkg.esp8266.yaml
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  bmp280: !include
    file: .pkg.bmp280.yaml
    vars:
      name: Cocina
  ir_ac_hack: !include
    file: .pkg.ir_ac_hack.yaml
    vars:
      pin_number: GPIO14

climate:
  - platform: coolix
    receiver_id: ir_hack_rx
    sensor: bmp280_temperature
    name: AC Cocina
    supports_heat: false
