substitutions:
  device_name: eh-comedor-window
  friendly_name: Comedor Ventana

packages:
  board: !include .pkg.esp8266.yaml
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml

esp8266:
  board: nodemcu
  
logger:
  level: VERBOSE

globals:
  - id: tilt_pos
    type: float

servo:
  - output: "ob_t"
    id: ob_tilt
    restore: true
    min_level: 3%
    max_level: 12%
    transition_length: 5s
    auto_detach_time: 2s

output:
  - platform: esp8266_pwm ## this is for the servo
    id: "ob_t"
    pin: D0
    frequency: 50 Hz

cover:
  - platform: template
    name: Persiana comedor
    tilt_lambda: |-
      return id(tilt_pos);
    tilt_action:
      - lambda: |-
          id(ob_tilt).write((1 - tilt) * 2 - 1);
          id(tilt_pos) = tilt;
