esphome:
  name: eh-comedor
  platform: ESP8266
  board: nodemcu
  # Use a local copy of ESPHome
  includes:
    - arduino_port_expander.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

i2c:
  id: i2ccomponent

logger:
  level: DEBUG

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExpander(i2ccomponent, 0x08);
      return {ape_component};

output:
  - platform: custom
    type: binary
    lambda: |-
      return {ape_binary_output(ape, 7),
              ape_binary_output(ape, 6),
              ape_binary_output(ape, 5),
              ape_binary_output(ape, 4)};
    outputs:
      - id: gpio_relay_1
        inverted: true
      - id: gpio_relay_2
        inverted: true
      - id: gpio_relay_3
        inverted: true
      - id: gpio_relay_4
        inverted: true

light:
  - platform: binary
    id: spot_puerta
    name: "Spot Puerta"
    output: gpio_relay_1
  - platform: binary
    id: spots_living
    name: "Spots Living"
    output: gpio_relay_2
  - platform: binary
    id: comedor
    name: "Luz Comedor"
    output: gpio_relay_3
  - platform: binary
    id: garage
    name: "Garage"
    output: gpio_relay_4

binary_sensor:
  - platform: status
    name: "Comedor Status"
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 3),
              ape_binary_sensor(ape, 2),
              ape_binary_sensor(ape, 8),
              ape_binary_sensor(ape, 9),
              ape_binary_sensor(ape, 10),
              ape_binary_sensor(ape, 11),
              ape_binary_sensor(ape, 14),
              ape_binary_sensor(ape, 15)
              };
    binary_sensors:
      - name: "Switch Comedor Puerta 1"
        filters:
          delayed_on_off: 100ms
        internal: true
        on_state:
          then:
            - light.toggle: comedor
      - name: "Switch Comedor Puerta 2"
        filters:
          delayed_on_off: 100ms
        internal: true
        on_state:
          then:
            - switch.toggle: spots
      - name: "Switch Comedor Puerta 3"
        filters:
          delayed_on_off: 100ms
        internal: true
        on_state:
          then:
            - light.toggle: garage
      - name: "Switch Garage 1"
        filters:
          delayed_on_off: 100ms
        internal: true
        on_state:
          then:
            - light.toggle: garage
      - name: "Switch Garage 2"
        filters:
          delayed_on_off: 100ms
      - name: "Switch Garage 3"
        filters:
          delayed_on_off: 100ms
      - name: "Ventana Comedor Oeste"
        filters:
          delayed_on_off: 100ms
        device_class: window
      - name: "Movimiento Comedor"
        filters:
          delayed_on_off: 100ms
        device_class: motion

switch:
  - platform: template
    id: spots
    optimistic: true
    internal: true
    turn_on_action:
      - light.turn_on: spots_living
      - light.turn_on: spot_puerta
    turn_off_action:
      - light.turn_off: spots_living
      - light.turn_off: spot_puerta

button:
  - platform: restart
    name: "Comedor Restart"
# ESP                     Female Header
#                           11  12        PS
# 0 RX   Arduino            13  14        PS
# 1 TX                      15  16        PS
#                           17  18        PS
#          Male header
#  10 pin: 2 4 6 8 10         Male Header 1 GPIO0
#          1 3 5 7 9                      2 ESP RX
#                                         3 ESP TX
#                                         4 GND

# RX:
# TX:

#    RIBBON        PIN
# 1: black        +12 V in
# 2: white        APE 3         SW Comedor 1 TAN
# 3: gray         GPIO14
# 4: purple       APE 2         SW Comedor 2 BROWN
# 5: blue         GPIO12
# 6: green        APE 8         SW Comedor 3 RED
# 7: yellow   ->  GROUND
# 8: orange       APE A1        PIR
# 9: red          APE A0        Reed Window WEST
# 10: brown       +5V

# 11              GND
# 12              3.3V
# 13              APE 9         SW Garage 1 TAN
# 14              APE 10        SW Garage 2 BROWN
# 15              APE 13         OUTPUT only
# 16              APE 11        SW Garage 2 RED
# 17              APE 12
# 18

