substitutions:
  device_name: eh-comedor-ac
  friendly_name: Comedor AC

packages:
  board: !include .pkg.esp8266.yaml
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  bmp280: !include
    file: .pkg.bmp280.yaml
    vars:
      name: Comedor
  ir_ac_hack: !include
    file: .pkg.ir_ac_hack.yaml
    vars:
      pin_number: GPIO14

climate:
  - platform: whirlpool
    name: AC Comedor
    id: whirlpool_ac
    sensor: bmp280_temperature
    receiver_id: ir_hack_rx
    model: DG11J1-91
    on_control:
      then:
        - script.execute: await_state_check

binary_sensor:
  - platform: gpio
    id: whirlpool_on
    name: Whirlpool on
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    filters:
      - invert:
      - delayed_off: 200ms

globals:
  - id: ac_mode_global
    type: int
    initial_value: "climate::ClimateMode::CLIMATE_MODE_COOL"
    restore_value: yes

interval:
  - interval: 10s
    then:
      - if:
          condition:
            - not:
                - script.is_running: await_state_check
          then:
            - script.execute: update_ac_state

script:
  - id: await_state_check
    then:
      - delay: 2s # this time takes LCD to follow command, i.e. if I turn on AC it takes this time to turn on the LCD (and GPIO13)
      - script.execute: update_ac_state
  - id: update_ac_state
    then:
      # keep active non off known state
      - lambda: |-
          auto ac_mode = id(whirlpool_ac)->mode;
          if (ac_mode != climate::ClimateMode::CLIMATE_MODE_OFF)
            id(ac_mode_global) = ac_mode;
          bool is_on = id(whirlpool_on).state;
          id(whirlpool_ac).powered_on_assumed = is_on;
          ESP_LOGD("main", "Stored ac mode: %d current: %d whirlpool on: %d", id(ac_mode_global), ac_mode, is_on);
          if (is_on &&
              (ac_mode == climate::ClimateMode::CLIMATE_MODE_OFF
              || ac_mode == climate::ClimateMode::CLIMATE_MODE_FAN_ONLY))
              {
                ac_mode = static_cast<climate::ClimateMode>(id(ac_mode_global));
                if (ac_mode == climate::ClimateMode::CLIMATE_MODE_OFF
                    || ac_mode == climate::ClimateMode::CLIMATE_MODE_FAN_ONLY)
                    {
                      // Can't be assume auto
                      ac_mode = climate::ClimateMode::CLIMATE_MODE_AUTO;
                    }
                ESP_LOGD("main", "Ac is on but reporting something else...");
                id(whirlpool_ac).mode = ac_mode;
              }
          if (!is_on &&
              (ac_mode != climate::ClimateMode::CLIMATE_MODE_OFF
              && ac_mode != climate::ClimateMode::CLIMATE_MODE_FAN_ONLY))
              {
                ESP_LOGD("main", "Ac is off but reporting something else...");
                id(whirlpool_ac).mode = climate::ClimateMode::CLIMATE_MODE_OFF;
              }
