substitutions:
  device_name: eh-comedor
  friendly_name: Comedor

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml
  ape: !include .pkg.ape.yaml

light:
  - platform: binary
    id: spot_puerta
    name: "Spot Puerta"
    output: ape_relay_1
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: spots_living
    name: "Spots Living"
    output: ape_relay_2
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: comedor
    name: "Luz Comedor"
    output: ape_relay_3
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: garage
    name: "Garage"
    output: ape_relay_4

binary_sensor:
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 3 
      mode:
        input: true
        pullup: true
    name: "Switch Comedor Puerta 1"
    filters:
      delayed_on_off: 100ms
    internal: true
    on_state:
      then:
        - light.toggle: comedor
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 2  
      mode:
        input: true
        pullup: true
    name: "Switch Comedor Puerta 2"
    filters:
      delayed_on_off: 100ms
    internal: true
    on_state:
      then:
        - switch.toggle: spots
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 8
      mode:
        input: true
        pullup: true
    name: "Switch Comedor Puerta 3"
    filters:
      delayed_on_off: 100ms
    internal: true
    on_state:
      then:
        - light.toggle: garage
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 9
      mode:
        input: true
        pullup: true
    name: "Switch Garage 1"
    filters:
      delayed_on_off: 100ms
    internal: true
    on_state:
      then:
        - light.toggle: garage
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 10
      mode:
        input: true
        pullup: true
    name: "Switch Garage 2"
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 11
      mode:
        input: true
        pullup: true
    name: "Switch Garage 3"
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 14
      mode:
        input: true
        pullup: true
    name: "Ventana Comedor Oeste"
    filters:
      delayed_on_off: 100ms
    device_class: window
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 15
      mode:
        input: true
        pullup: true
    name: "Movimiento Comedor"
    filters:
      delayed_on_off: 100ms
    device_class: motion

switch:
  - platform: template
    id: spots
    optimistic: true
    internal: true
    turn_on_action:
      - light.turn_on: spots_living
      - light.turn_on: spot_puerta
    turn_off_action:
      - light.turn_off: spots_living
      - light.turn_off: spot_puerta
# ESP                     Female Header
#                           11  12        PS
# 0 RX   Arduino            13  14        PS
# 1 TX                      15  16        PS
#                           17  18        PS
#          Male header
#  10 pin: 2 4 6 8 10         Male Header 1 GPIO0
#          1 3 5 7 9                      2 ESP RX
#                                         3 ESP TX
#                                         4 GND

# RX:
# TX:

#    RIBBON        PIN
# 1: black        +12 V in
# 2: white        APE 3         SW Comedor 1 TAN
# 3: gray         GPIO14
# 4: purple       APE 2         SW Comedor 2 BROWN
# 5: blue         GPIO12
# 6: green        APE 8         SW Comedor 3 RED
# 7: yellow   ->  GROUND
# 8: orange       APE A1        PIR
# 9: red          APE A0        Reed Window WEST
# 10: brown       +5V

# 11              GND
# 12              3.3V
# 13              APE 9         SW Garage 1 TAN
# 14              APE 10        SW Garage 2 BROWN
# 15              APE 13         OUTPUT only
# 16              APE 11        SW Garage 2 RED
# 17              APE 12
# 18

