substitutions:
  device_name: eh-dor-sur
  friendly_name: Dormitorio Sur

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml
  ape: !include .pkg.ape.yaml

light:
  - platform: binary
    id: luz_techo
    name: "Dormitorio Sur"
    output: ape_relay_1
  - platform: binary
    id: luz_spot_pared
    name: "Dormitorio Sur Cama Pared"
    output: ape_relay_2
  - platform: binary
    id: luz_spot_ventana
    name: "Dormitorio Sur Cama Ventana"
    output: ape_relay_3

sensor:
  - platform: homeassistant
    entity_id: light.dormitorio_sur_rgb
    id: colors_led_brightness
    attribute: brightness

binary_sensor:
  - platform: homeassistant
    id: colors_led_feedback
    entity_id: light.dormitorio_sur_rgb
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 2 # ribbon purple
      mode:
        input: true
        pullup: true
    name: "Switch Puerta 1"
    internal: true
    on_state:
      then:
        - light.toggle: luz_techo
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 16 # ribbon white
      mode:
        input: true
        pullup: true
    name: "Switch puerta 2"
    internal: true
    on_state:
      then:
        if:
          condition:
            or:
              - light.is_on: luz_spot_ventana
              - light.is_on: luz_spot_pared
          then:
            - light.turn_off: luz_spot_ventana
            - light.turn_off: luz_spot_pared
          else:
            - light.turn_on: luz_spot_ventana
            - light.turn_on: luz_spot_pared
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 8 # ribbon green
      mode:
        input: true
        pullup: true
    name: "${friendly_name} switch puerta 3"
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 1
      mode:
        input: true
        pullup: true
    name: "Switch Cama Pared 1" # Enciende luces
    internal: true
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_off: colors_led_feedback
            then:
              script.execute: color_leds_lights_low
            else:
              if:
                condition:
                  sensor.in_range:
                    id: colors_led_brightness
                    below: 100
                then:
                  script.execute: color_leds_lights_high
                else:
                  if:
                    condition:
                      light.is_off: luz_spot_pared
                    then:
                      light.turn_on: luz_spot_pared
                    else:
                      if:
                        condition:
                          light.is_off: luz_techo
                        then:
                          light.turn_on: luz_techo
                        else:
                          light.turn_on: luz_spot_ventana

  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 0
      mode:
        input: true
        pullup: true
    name: "Switch Cama Pared 2" # Apaga luces
    internal: true
    on_state:
      then:
        - if:
            condition:
              light.is_on: luz_techo
            then:
              light.turn_off: luz_techo
            else:
              if:
                condition:
                  light.is_on: luz_spot_pared
                then:
                  light.turn_off: luz_spot_pared
                else:
                  if:
                    condition:
                      binary_sensor.is_on: colors_led_feedback
                    then:
                      if:
                        condition:
                          sensor.in_range:
                            id: colors_led_brightness
                            above: 100
                        then:
                          script.execute: color_leds_lights_low
                        else:
                          script.execute: color_leds_lights_off
                    else:
                      light.turn_off: luz_spot_ventana
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 10
      mode:
        input: true
        pullup: true
    name: "Switch Cama Ventana 1" # Enciende luces
    internal: true
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_off: colors_led_feedback
            then:
              script.execute: color_leds_lights_low
            else:
              if:
                condition:
                  sensor.in_range:
                    id: colors_led_brightness
                    below: 100
                then:
                  script.execute: color_leds_lights_high
                else:
                  if:
                    condition:
                      light.is_off: luz_spot_ventana
                    then:
                      light.turn_on: luz_spot_ventana
                    else:
                      if:
                        condition:
                          light.is_off: luz_techo
                        then:
                          light.turn_on: luz_techo
                        else:
                          light.turn_on: luz_spot_pared

  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 9
      mode:
        input: true
        pullup: true
    name: "Switch Cama Ventana 2"
    internal: true
    on_state:
      then:
        - if:
            condition:
              light.is_on: luz_techo
            then:
              light.turn_off: luz_techo
            else:
              if:
                condition:
                  light.is_on: luz_spot_ventana
                then:
                  light.turn_off: luz_spot_ventana
                else:
                  if:
                    condition:
                      binary_sensor.is_on: colors_led_feedback
                    then:
                      if:
                        condition:
                          sensor.in_range:
                            id: colors_led_brightness
                            above: 100
                        then:
                          script.execute: color_leds_lights_low
                        else:
                          script.execute: color_leds_lights_off
                    else:
                      light.turn_off: luz_spot_pared

  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 14
      mode:
        input: true
        pullup: true
    name: "Ventana Dormitorio Sur"
    device_class: window

script:
  - id: color_leds_lights_low
    then:
      homeassistant.service:
        service: light.turn_on
        data:
          entity_id: light.dormitorio_sur_rgb
          brightness: "80"

  - id: color_leds_lights_high
    then:
      homeassistant.service:
        service: light.turn_on
        data:
          entity_id: light.dormitorio_sur_rgb
          brightness: "200"

  - id: color_leds_lights_off
    then:
      homeassistant.service:
        service: light.turn_off
        data:
          entity_id: light.dormitorio_sur_rgb
