substitutions:
  device_name: eh-dor-nor
  friendly_name: Dormitorio Norte

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml
  ape: !include .pkg.ape.yaml

light:
  - platform: binary
    id: techo
    name: "${friendly_name} luz techo"
    output: ape_relay_1
  - platform: binary
    id: cama_pared
    name: "${friendly_name} luz cama pared"
    output: ape_relay_2
  - platform: binary
    id: cama_ventana
    name: "${friendly_name} luz cama ventana"
    output: ape_relay_3

switch:
  - platform: output
    output: ape_relay_4
    id: tomas_electricos
    name: "${friendly_name} tomas electricos"
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 2
      mode:
        input: true
        pullup: true
    name: "${friendly_name} switch puerta 1"
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: techo
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 3
      mode:
        input: true
        pullup: true
    name: "${friendly_name} switch puerta 2"
    filters:
      delayed_on_off: 200ms
    on_state:
      then:
        if:
          condition:
            or:
              - light.is_on: cama_ventana
              - light.is_on: cama_pared
          then:
            - light.turn_off: cama_ventana
            - light.turn_off: cama_pared
          else:
            - light.turn_on: cama_ventana
            - light.turn_on: cama_pared
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 8
      mode:
        input: true
        pullup: true
    name: "${friendly_name} switch puerta 3"
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 11
      mode:
        input: true
        pullup: true
    name: "${friendly_name} switch cama pared 1"
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: cama_pared
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 12
      mode:
        input: true
        pullup: true
    name: "${friendly_name} switch cama pared 2"
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: techo
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 14
      mode:
        input: true
        pullup: true
    name: "${friendly_name} switch cama ventana 1"
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: cama_ventana
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 15
      mode:
        input: true
        pullup: true
    name: "${friendly_name} switch cama ventana 2"
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: techo
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 9
      mode:
        input: true
        pullup: true
    name: "${friendly_name} ventana"
    filters:
      delayed_on_off: 100ms
    device_class: window

remote_transmitter:
  pin: GPIO14 # ribbon gray
  carrier_duty_percent: 50%
# New board pinout:

# ESP                     Female Header
#                           11  12        PS
# 0 RX   Arduino            13  14        PS
# 1 TX                      15  16        PS
#                           17  18        PS
#          Male header
#  10 pin: 2 4 6 8 10
#          1 3 5 7 9
#

# RX:
# TX:

#    RIBBON        PIN
# 1: black        +12 V in
# 2: white        APE 3            switch puerta 2
# 3: gray         GPIO12
# 4: purple       APE 2            switch puerta 1
# 5: blue         GPIO13
# 6: green        APE 8            switch puerta 3
# 7: yellow   ->  GROUND
# 8: orange       APE A1           switch cama ventana 2
# 9: red          APE A0           switch cama ventana 1
# 10: brown       +5V

# 11 GND
# 12 3.3V
# 13 APE 9                         reed switch ventana
# 14 APE 10                        reed switch puerta
# 15 APE 13                        pir
# 16 APE 11                        switch cama pared 1
# 17 APE 12                        switch cama pared 2
# 18

