substitutions:
  device_name: eh-dor-este
  friendly_name: Dormitorio Este

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml
  ape: !include .pkg.ape.yaml

light:
  - platform: binary
    id: luz_dormitorio_este
    name: "Dormitorio Este"
    output: ape_relay_1
  - platform: binary
    id: luz_dormitorio_este_cama
    name: "Dormitorio Este Cama"
    output: ape_relay_2

binary_sensor:
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 15 # A1 ribbon orange
      mode:
        input: true
        pullup: true
    name: "Switch Puerta 1"
    internal: true
    on_state:
      then:
        - light.toggle: luz_dormitorio_este
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 3 # ribbon white
      mode:
        input: true
        pullup: true
    name: "Switch puerta 2"
    internal: true
    on_state:
      then:
        - light.toggle: luz_dormitorio_este_cama
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 8 # ribbon green
      mode:
        input: true
        pullup: true
    name: "Switch Cama 1"
    internal: true
    on_state:
      then:
        - light.toggle: luz_dormitorio_este
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 2 # ribbon purple
      mode:
        input: true
        pullup: true
    name: "Switch Cama 2"
    internal: true
    on_state:
      then:
        - light.toggle: luz_dormitorio_este_cama
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 14 # A0 ribbon red
      mode:
        input: true
        pullup: true
    name: "Ventana Dormitorio Este"
    device_class: window
