esphome:
  name: eh-dor-nor-ac
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

substitutions:
  rgb_receiver_light_entity: light.dormitorio_norte_rgb

packages:
  rgb_receiver: !include rgb_receiver.package.yaml

logger:
  level: DEBUG
  baud_rate: 0

remote_receiver:
  id: rcvr
  pin:
    number: GPIO14
    inverted: True
    mode: OUTPUT_OPEN_DRAIN
  tolerance: 45%

remote_transmitter:
  - id: receiver_hack
    carrier_duty_percent: 100%
    pin:
      number: GPIO14
      inverted: true
      mode: OUTPUT_OPEN_DRAIN
  - id: ir_LED
    carrier_duty_percent: 50%
    pin: GPIO12

climate:
  - platform: coolix
    sensor: temp_norte
    name: "AC Dormitorio Norte"
    supports_heat: True
    supports_cool: True
    receiver_id: rcvr
    transmitter_id: receiver_hack

switch:
  - platform: restart
    name: "Dormitorio Norte Ac Restart"

  - platform: template
    name: Dor Nor Netflix
    turn_on_action:
      - remote_transmitter.transmit_nec:
          transmitter_id: ir_LED
          address: 0xFD
          command: 0xC23D # 0x43
  - platform: template
    name: Dor Nor TV Power

    turn_on_action:
      - remote_transmitter.transmit_nec:
          transmitter_id: ir_LED
          address: 0x00FD
          command: 0xC03F

i2c:
  id: i2c_component

sensor:
  - platform: bmp280
    temperature:
      id: temp_norte
      name: "Temperature Dor Norte"
      oversampling: 1x
    pressure:
      name: "Presion Dor Norte"
      oversampling: 1x
    address: 0x76
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Dormitorio Norte AC Status"
