substitutions:
  device_name: eh-dor-este-ac
  friendly_name: Dormitorio Este AC

packages:
  board: !include .pkg.esp8266.yaml
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  bmp280: !include
    file: .pkg.bmp280.yaml
    vars:
      name: Dormitorio Norte
  ir_ac_hack: !include
    file: .pkg.ir_ac_hack.yaml
    vars:
      pin_number: GPIO14

logger:
  baud_rate: 0

climate:
  - platform: coolix
    sensor: bmp280_temperature
    name: "AC Dormitorio Este"
    supports_heat: True
    supports_cool: True
    receiver_id: ir_hack_rx
    transmitter_id: ir_hack_tx
