esphome:
  name: eh-estudio-ac

esp8266:
  board: esp12e
  restore_from_flash: true

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

dallas:
  pin: GPIO2
  update_interval: 60s

binary_sensor:
  - platform: status
    name: "Estudio AC Status"

sensor:
  - platform: dallas
    #address: 0xF77AF93F12646128
    index: 0
    id: dallas_temp
    internal: true

remote_receiver:
  id: rcvr
  pin:
    number: GPIO14
    inverted: True
    mode: OUTPUT_OPEN_DRAIN
  tolerance: 45%

remote_transmitter:
  - id: receiver_hack
    carrier_duty_percent: 100%
    pin:
      number: GPIO14
      inverted: true
      mode: OUTPUT_OPEN_DRAIN

climate:
  - platform: tcl112
    receiver_id: rcvr
    sensor: dallas_temp
    name: "AC Estudio"
