# Wiring
#     L (volt measure)   I current measure
#  L1  Brown              Green
#  L2  Red                Orange
#  L3  Black              Yellow
#
#  Neutral: Blue
substitutions:
  device_name: eh-energia
  friendly_name: Energia

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml

esphome:
  on_boot:
    then:
      - delay: 2s
      - light.turn_on:
          id: led_strip
          effect: "Voltage"

logger:
  baud_rate: 0

uart:
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX
  #stop_bits: 2

sensor:
  - platform: pzemac
    id: pzem1
    address: 0x01
    current:
      name: ${friendly_name} L1 Corriente
    voltage:
      id: l1_volt
      name: ${friendly_name} L1 Voltage
    frequency:
      name: ${friendly_name} L1 Frecuencia
    energy:
      name: ${friendly_name} L1 Energía
      filters:
        - lambda: |-
            if (x < 40000000.0)
              return x;
            else
              return {};

    power:
      name: "${friendly_name} L1 Potencia"
    power_factor:
      name: ${friendly_name} L1 Factor de potencia
    update_interval: never

  - platform: pzemac
    id: pzem2
    address: 2
    current:
      name: ${friendly_name} L2 Corriente
    voltage:
      id: l2_volt
      name: ${friendly_name} L2 Voltage
    frequency:
      name: ${friendly_name} L2 Frecuencia
    energy:
      name: ${friendly_name} L2 Energía
      filters:
        - lambda: |-
            if (x < 40000000.0)
              return x;
            else
              return {};

    power:
      name: "${friendly_name} L2 Potencia"
    power_factor:
      name: ${friendly_name} L2 Factor de potencia
    update_interval: never
  - platform: pzemac
    id: pzem3
    address: 3
    current:
      name: ${friendly_name} L3 Corriente
    voltage:
      id: l3_volt
      name: ${friendly_name} L3 Voltage
    frequency:
      name: ${friendly_name} L3 Frecuencia
    energy:
      name: ${friendly_name} L3 Energía
      filters:
        - lambda: |-
            if (x < 40000000.0)
              return x;
            else
              return {};

    power:
      name: "${friendly_name} L3 Potencia"
    power_factor:
      name: ${friendly_name} L3 Factor de potencia
    update_interval: never

light:
  - platform: neopixelbus
    pin: GPIO2
    num_leds: 3
    variant: WS2812
    id: led_strip
    name: Energia Strip
    effects:
      - addressable_lambda:
          name: Voltage
          update_interval: 1s
          lambda: |-
            struct EnergyLEDCallbacks {
              static auto voltage_color(float voltage) {
                if (voltage < 160)
                  return Color(255, 0, 0); // Red: line down
                if (voltage < 200)
                  return Color(204, 102, 0); // Orange: low
                if (voltage < 240)
                  return Color(0, 140, 0); // Green: about right 200-240 VAC
                return Color(170, 170, 0); // Yellow: over voltage
              }
            };

            it[0] = EnergyLEDCallbacks::voltage_color(id(l1_volt).state);
            it[1] = EnergyLEDCallbacks::voltage_color(id(l2_volt).state);
            it[2] = EnergyLEDCallbacks::voltage_color(id(l3_volt).state);
      - addressable_lambda:
          name: Random
          update_interval: 1s
          lambda: |-
            it[0] = Color::random_color();
            it[1] = Color::random_color();
            it[2] = Color::random_color();

button:
  - platform: template
    name: Reset PZEM
    on_press:
      then:
        globals.set:
          id: reset_pzem
          value: !lambda return true;

globals:
  - id: reset_pzem
    type: boolean

interval:
  - interval: 6s
    then:
      - component.update: pzem1
      - delay: 2s
      - component.update: pzem2
      - delay: 2s
      - component.update: pzem3
      - if:
          condition:
            lambda: !lambda return id(reset_pzem);
          then:
            - globals.set:
                id: reset_pzem
                value: !lambda return false;
            - delay: 30ms
            - pzemac.reset_energy: pzem1
            - delay: 300ms
            - pzemac.reset_energy: pzem2
            - delay: 300ms
            - pzemac.reset_energy: pzem3
