substitutions:
  device_name: eh-estudio-ac
  friendly_name: Estudio AC

packages:
  board: !include .pkg.esp8266.yaml
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  ir_ac_hack: !include
    file: .pkg.ir_ac_hack.yaml
    vars:
      pin_number: GPIO14

dallas:
  pin: GPIO2

sensor:
  - platform: dallas
    address: 0xf77af93f12646128
    id: dallas_temperature

climate:
  - platform: tcl112
    receiver_id: ir_hack_rx
    sensor: dallas_temperature
    name: AC Estudio

