substitutions:
  device_name: eh-estudio
  friendly_name: Estudio

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml
  ape: !include .pkg.ape.yaml

light:
  - platform: binary
    id: luz_estudio
    name: "Luz estudio"
    output: ape_relay_1
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: luz_pasillo
    name: "Luz pasillo"
    output: ape_relay_2
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: luz_banio
    name: "Luz baño"
    output: ape_relay_3
    restore_mode: RESTORE_DEFAULT_OFF

fan:
  - platform: binary
    id: extractor_banio
    restore_mode: ALWAYS_OFF
    output: ape_relay_4
    name: "Extractor baño"

binary_sensor:
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 17 # A3
      mode:
        input: true
        pullup: true
    name: "Switch estudio puerta 1"
    internal: true
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_estudio
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 2
      mode:
        input: true
        pullup: true
    name: "Switch estudio puerta 2" # DI2
    internal: true
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_pasillo
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 16 # A2
      mode:
        input: true
        pullup: true
    name: "Switch estudio galeria 1"
    internal: true
    filters:
      delayed_on_off: 100ms
    on_state:
      - light.toggle: luz_estudio
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 8
      mode:
        input: true
        pullup: true
    name: "Switch Estudio Galeria"
    internal: true
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 15 # A1
      mode:
        input: true
        pullup: true
    name: "Switch Estudio Patio"
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 12
      mode:
        input: true
        pullup: true
    name: "Ventana Comedor Norte"
    filters:
      delayed_on_off: 100ms
    device_class: window
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 10
      mode:
        input: true
        pullup: true
    name: "Switch escalera 1"
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 9
      mode:
        input: true
        pullup: true
    name: "Switch escalera 2"
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 13
      mode:
        input: true
        pullup: true
    name: "Switch baño 1"
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_banio
        - script.execute: keep_banio_light
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 11
      mode:
        input: true
        pullup: true
    name: "Switch baño 2"
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 14 #A0
      mode:
        input: true
        pullup: true
    name: "Movimiento estudio"
    filters:
      delayed_on_off: 100ms
    device_class: motion
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 3
      mode:
        input: true
        pullup: true
    name: "Puerta Baño"
    filters:
      delayed_on_off: 100ms
    id: puerta_banio
    device_class: door
    on_state: # Open or close door
      then:
        - script.execute: auto_off_extractor
        - if:
            condition:
              light.is_on: luz_banio
            then:
              script.execute: auto_off_luz_banio

    on_press: # Open door
      then:
        - if:
            condition:
              not:
                script.is_running: keep_banio_light
            then:
              - script.execute: auto_off_luz_banio

script:
  - id: keep_banio_light
    mode: restart
    then:
      - delay: 5s

  - id: auto_off_luz_banio
    mode: restart
    then:
      - light.turn_on: luz_banio
      - if:
          condition:
            binary_sensor.is_on: puerta_banio # open
          then:
            - delay: 5 min
          else:
            - delay: 12 min
      - light.turn_off: luz_banio

  - id: auto_off_extractor
    mode: restart
    then:
      - fan.turn_on: extractor_banio
      - logger.log: Stopping fan in 10 minutes
      - delay: 10 min
      - fan.turn_off: extractor_banio

###
# module info:
# Male Header:
# GND - White | DI2 - Pur |  DI8 - Greeen |  NC       | A2 Brown
# 12V - Black | A1 - Gray |  5V -    Blue |  A0 - Yel | A3 Red

# Female Header
# GND  |  3.3V
# DI9  |  DI10  -> puintos escalera
# DI13 |  DI11  -> puntos baño
# DI12 |  DI3  ->  DI12 Ventana, DI3 Puerta baño (Rojo)

# Cables entre estudio - baño
# Cable 1
# Blanco - GND
# Azul   - 12V          -
# Marron - IR LED       - GPIO14
# Amaril - PIR          - r Yell
# Rojo   - Puerta SW 1  - r Red
# Cable 2
# Blanco - 5V LED
# Rojo   - Puerta SW 2  - r Purple
# Marron - Galeria SW 1 - r Green
# Amaril - Galeria SW 2 - r Brown
# Azul   - Galeria SW 3 - r Gray

# cable baño
# rojo: Puerta
# blanco: 0V
# marron: DHT Data
# azul: 5V

