esphome:
  name: eh-estudio-test

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

esp8266:
  board: nodemcu

substitutions:
  device_name: "Estudio test"
api:
  services:
    service: set_addr
    variables:
      address: int
    then:
      number.set:
        id: pzem_addr
        value: !lambda "return address;"

ota:

logger:
  #baud_rate: 0
  level: DEBUG

# sensor:
#   - platform: pzemac
#     address: 3
#     current:
#       name: ${device_name} Corriente
#     voltage:
#       name: ${device_name} Voltage
#     frequency:
#       name: ${device_name} Frecuencia
#     energy:
#       name: ${device_name} Energía
#     power:
#       name: "${device_name} Potencia"
#     power_factor:
#       name: ${device_name} Factor de potencia
#     update_interval: 5s

uart:
  baud_rate: 9600
  tx_pin: GPIO12
  rx_pin: GPIO14

modbus_controller:
  address: 248 # broadcast address, you can communicate with any connected device regardless of it address

number:
  - platform: modbus_controller
    id: pzem_addr
    name: "pzem_addr"
    address: 0x2 # this is the address registry number, and it is not related to device address, do not change
    value_type: U_WORD
