substitutions:
  device_name: eh-galeria
  friendly_name: Galeria

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml
  ape: !include .pkg.ape.yaml

output:
  - platform: gpio
    id: ardu_13_npn
    inverted: true
    pin:
      arduino_port_expander: ape
      number: 13

light:
  - platform: binary
    id: galeria
    name: "Galeria"
    output: ape_relay_1
    effects:
      - strobe:
          name: Strobe
  - platform: binary
    id: patio_proyector_este
    name: "Patio Proyector Este"
    output: ape_relay_2
    effects:
      - strobe:
          name: Strobe
  - platform: binary
    id: patio_proyector_oeste
    name: "Patio Proyector Oeste"
    output: ape_relay_3
    effects:
      - strobe:
          name: Strobe
  - platform: binary
    id: sirena_led
    name: "LED Sirena"
    output: ardu_13_npn
    effects:
      - strobe:
          name: Strobe
      - strobe:
          name: Flash
          colors:
            - state: True
              brightness: 100%
              duration: 500ms
            - state: False
              duration: 250ms

remote_transmitter:
  pin: GPIO12
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%

switch:
  - platform: output
    id: sirena
    name: "Sirena"
    output: ape_relay_4
    on_turn_on:
      then:
        - script.execute: auto_off_siren

  - platform: template
    id: C3_Lock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011010100001100"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C3_UnLock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011010100110000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C3_Bajar
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011010100000011"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C3_Subir
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011010111000000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms

  - platform: template
    id: C4_Lock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110111010100001100001100"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C4_UnLock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110111010100001100110000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C4_Bajar
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110111010100001111000000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C4_Subir
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110111010100001100000011"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms

  - platform: template
    id: C9_Lock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011110100001100"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C9_UnLock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011110100110000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C9_Bajar
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011110100000011"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C9_Subir
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011110111000000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms

  - platform: template
    name: Comando Activacion Cerco
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "1011110110111101111000100101"
          protocol: 6
          repeat:
            times: 2
            wait_time: 2ms

globals:
  - id: disable_cover_commands
    type: boolean
    initial_value: "false"

cover:
  - platform: feedback
    device_class: shutter
    name: "Cortina 9 Muro"
    id: cover_muro
    open_action:
      - if:
          condition:
            lambda: "return !id(disable_cover_commands);"
          then:
            - switch.turn_on: C9_Subir

    open_duration: 40s
    close_action:
      - if:
          condition:
            lambda: "return !id(disable_cover_commands);"
          then:
            - switch.turn_on: C9_Bajar
    close_duration: 40s
    stop_action:
      - switch.turn_on: C9_UnLock
    has_built_in_endstop: true
    assumed_state: false
    close_endstop: bs_muro
    max_duration: 50s
    direction_change_wait_time: 2s
    acceleration_wait_time: 800ms

  - platform: feedback
    device_class: shutter
    name: "Cortina 4 Centro"
    id: cover_centro
    open_action:
      - if:
          condition:
            lambda: "return !id(disable_cover_commands);"
          then:
            - switch.turn_on: C4_Subir
    open_duration: 40s
    close_action:
      - if:
          condition:
            lambda: "return !id(disable_cover_commands);"
          then:
            - switch.turn_on: C4_Bajar
    close_duration: 40s
    stop_action:
      - switch.turn_on: C4_UnLock
    has_built_in_endstop: true
    assumed_state: false
    close_endstop: bs_centro
    max_duration: 50s
    direction_change_wait_time: 2s
    acceleration_wait_time: 900ms

  - platform: feedback
    device_class: shutter
    name: "Cortina 3 Pasillo"
    id: cover_pasillo
    open_action:
      - if:
          condition:
            lambda: "return !id(disable_cover_commands);"
          then:
            - switch.turn_on: C3_Subir
    open_duration: 40s
    close_action:
      - if:
          condition:
            lambda: "return !id(disable_cover_commands);"
          then:
            - switch.turn_on: C3_Bajar
    close_duration: 40s
    stop_action:
      - switch.turn_on: C3_UnLock
    has_built_in_endstop: true
    assumed_state: false
    close_endstop: bs_pasillo
    max_duration: 50s
    direction_change_wait_time: 2s
    acceleration_wait_time: 900ms

binary_sensor:
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 8
      mode:
        input: true
        pullup: true
    name: "Puerta Frente"
    device_class: door
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 9
      mode:
        input: true
        pullup: true
    name: "Puerta Cocina"
    device_class: door
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 10
      mode:
        input: true
        pullup: true
    name: "Puerta Estudio"
    device_class: door
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 0
      mode:
        input: true
        pullup: true
    name: "Movimiento Galeria"
    device_class: motion
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 15
      mode:
        input: true
        pullup: true
    name: "Switch Galeria 1"
    internal: true
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: galeria
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 12
      mode:
        input: true
        pullup: true
    name: "Switch Galeria Proyectores"
    filters:
      delayed_on_off: 100ms
    on_state:
      then:
        - script.execute: toggle_proyectores
    internal: true
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 11
      mode:
        input: true
        pullup: true
    name: "Switch Galeria Patio"
    filters:
      delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 2
      mode:
        input: true
        pullup: true
    name: "Cortina Pasillo"
    id: bs_pasillo
    device_class: opening
    filters:
      - invert:
      - delayed_on_off: 2s
    internal: true
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 3
      mode:
        input: true
        pullup: true
    id: bs_centro
    filters:
      - invert:
      - delayed_on_off: 2s
    internal: true
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 14
      mode:
        input: true
        pullup: true
    name: "Cortina Muro"
    id: bs_muro
    device_class: opening
    filters:
      - invert:
      - delayed_on_off: 2s
    internal: true
  - platform: template
    name: "Cortina Centro"
    device_class: opening
    id: bs_centro_ha
    lambda: return !id(bs_centro).state;
  - platform: template
    name: "Cortina Muro"
    device_class: opening
    id: bs_muro_ha
    lambda: return !id(bs_muro).state;
  - platform: template
    name: "Cortina Pasillo"
    device_class: opening
    id: bs_pasillo_ha
    lambda: return !id(bs_pasillo).state;
  - platform: homeassistant
    entity_id: input_boolean.alarma_luces
    id: alarma_luces
    on_press:
      then:
        - light.turn_on:
            id: galeria
            effect: Strobe
        - light.turn_on:
            id: patio_proyector_este
            effect: Strobe
        - light.turn_on:
            id: patio_proyector_oeste
            effect: Strobe
        - light.turn_on:
            id: sirena_led
            effect: Strobe
    on_release:
      then:
        - light.turn_off: galeria
        - light.turn_off: patio_proyector_este
        - light.turn_off: patio_proyector_oeste
        - light.turn_off: sirena_led

script:
  - id: toggle_proyectores
    then:
      - light.toggle: patio_proyector_este
      - lambda: |-
          bool esteStatus;
          id(patio_proyector_este)->current_values_as_binary(&esteStatus);
          if (esteStatus)
          {
            ESP_LOGD("main", "Este switch %d, turning on", esteStatus);
            id(patio_proyector_oeste).turn_on().perform();
          }
          else
          {
            ESP_LOGD("main", "Este switch %d, turning off", esteStatus);
            id(patio_proyector_oeste).turn_off().perform();
          }
  - id: auto_off_siren
    mode: restart
    then:
      - delay: 10min
      - switch.turn_off: sirena

  # - id: verify_muro_cover_state
  #   then:
  #     - if:
  #         condition:
  #           - lambda: "return id(cover_muro).position == COVER_CLOSED;"
  #           - binary_sensor.is_off:
  #               id:
  #         then:
  #           logger.log: "hello"

dallas:
  pin: GPIO14
  update_interval: 600s

sensor:
  - platform: dallas
    address: 0x2771C02712646128
    name: Temperatura Patio
    filters:
      - filter_out: 85.0
###
# module info:
# Male Header:
# DI3   |  DI2  |  DI8 | T13   |  5V
# 12V   |  NC   |  NC  | GND   |  A0

# Female Header
# GND  |  3.3V
# DI9  |  DI10
# A1   |  DI11
# DI12 |  NC

# DI8 Puerta Frente
# DI9 Puerta cocina
# DI10 Puerta estudio
# DI11 Switch Galeria Patio
# DI12 Switch Galeria Proyectores
# DI0 Movimiento Galeria
# A1 # 15 # Switch Galeria 1

# DI3 Cortina
# DI2 Cortina
# A0 Cortina

