# JST PIN 1: Looking at the socket horizontally on the PCB, when the notches where latches are inseterd (cutoffs) are at the top, the pin one is at the left.
#            This is also red wire on lipo batteries balancer
substitutions:
  device_name: eh-lavadero
  friendly_name: Lavadero

packages:
  board: !include .pkg.esp32.arduino.yaml
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml  

binary_sensor:
# CN1: 3 PIN                        WIRE
# 1  +12V                         Brown
# 2  GPIO33 Puerta baño quincho   White/Blue
# 3  GPIO35 Tecla baño quincho    White/Brown

  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
    name: Puerta baño quincho
    device_class: door
  - platform: gpio
    pin: GPIO35
    name: Tecla baño quincho
    on_state:
      - light.toggle: luz_banio_quincho

# CN2: 5 PIN
# 1  +12V                         Brown
# 2  GPIO39 Puerta lavadero       White/Blue
# 3  GPIO36 Tecla lavadero 1      White/Brown
# 4  GPIO34 Tecla lavadero 2      Orange
# 5  GPIO32 Tecla lavadero 3      White/Orange

  - platform: gpio
    pin:
      number: GPIO39
      inverted: True
    name: Puerta lavadero
    device_class: door
  - platform: gpio
    pin: GPIO36
    name: Tecla lavadero 1
    on_state:
      then:
        - light.toggle: luz_lavadero

  - platform: gpio
    pin: GPIO34
    name: Tecla lavadero 2
  - platform: gpio
    pin: GPIO32
    name: Tecla lavadero 3

sensor:
  # - platform: dallas
  #   name: Parrilla Temperatura
  #   index: 0

output:
  - platform: gpio
    pin: GPIO2
    id: relay1
    inverted: true
  - platform: gpio
    pin: GPIO5
    id: relay2
    inverted: true
  - platform: gpio
    pin: GPIO4
    id: relay3
    inverted: true
  - platform: gpio
    pin: GPIO0
    id: relay4
    inverted: true


light:
  - platform: binary
    name: Luz pasillo quincho
    output: relay1
  - platform: binary
    name: Luz lavadero
    output: relay2
    id: luz_lavadero
  - platform: binary
    name: Luz baño quincho
    output: relay3
    id: luz_banio_quincho
  - platform: binary
    name: Luz Parrilla
    output: relay4
  - platform: fastled_clockless
    pin: GPIO12
    # name: Lavadero Status LED
    num_leds: 1
    chipset: WS2812
    id: status_led


# dallas:
#   pin: GPIO32
#   update_interval: 5s 
  