esphome:
  name: eh-piscina
  platformio_options:
    upload_speed: 921600

esp32:
  framework:
    type: esp-idf
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

logger:

api:

ota:
# ethernet:
#   type: LAN8720
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   clk_mode: GPIO0_IN
#   phy_addr: 1
#   power_pin: GPIO17
#   #enable_mdns: true

binary_sensor:
  - platform: status
    name: "Piscina Status"
  - platform: remote_receiver
    receiver_id: rx_rf
    id: btn_top
    name: CS_BotonArriba
    rc_switch_raw:
      protocol: 6
      code: "1011110110111101111000110101"
    #            1011110110111101111000110
    filters:
      - delayed_off: 1s

  - platform: remote_receiver
    receiver_id: rx_rf
    id: btn_bottom_left
    name: CS_BotonIzq
    rc_switch_raw:
      protocol: 6
      code: "1011110110111101111000100101"
    filters:
      - delayed_off: 1s

  - platform: remote_receiver
    id: btn_right
    name: CS_BotonDerecho
    rc_switch_raw:
      protocol: 6
      code: "1011110110111101111000010101"
    filters:
      - delayed_off: 1s

sensor:
  - platform: uptime
    name: Piscina uptime
  - platform: wifi_signal
    name: Piscina Wifi Signal
  - platform: dallas
    name: Piscina Temperatura sensor en tubo
    id: pipe_temperature_sensor
    entity_category: diagnostic
    index: 0
    on_value:
      then:
        - if:
            condition:
              and:
                - switch.is_on: switch_pool_pump
                - not:
                    - script.is_running: update_pool_temperature_await
            then:
              - sensor.template.publish:
                  id: pool_temperature_sensor
                  state: !lambda return x;

  - platform: template
    name: Piscina Temperatura
    id: pool_temperature_sensor
    device_class: temperature
    unit_of_measurement: ºC

status_led:
  pin: GPIO12

output:
  - platform: gpio
    pin: GPIO4
    id: relay2
    inverted: true
  - platform: gpio
    pin: GPIO2
    id: relay3
    inverted: true

switch:
  - platform: gpio
    id: switch_pool_pump
    name: Bomba Piscina
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO5
      inverted: true
    on_turn_on:
      - script.execute: update_pool_temperature_await
      # auto turn off after 3 hours
      - delay: 3h
      - switch.turn_off: switch_pool_pump
    on_turn_off:
      - script.stop: update_pool_temperature_await

  - platform: gpio
    name: Bomba riego
    pin:
      number: GPIO15
      inverted: true
  - platform: restart
    name: "Piscina Restart"

light:
  - platform: binary
    name: Luz fondo este
    output: relay2
  - platform: binary
    name: Luz fondo oeste
    output: relay3

remote_receiver:
  - id: rx_rf
    pin:
      number: GPIO14
    dump:
      - rc_switch

    # Settings to optimize recognition of RF devices
    tolerance: 50%
    filter: 150us
    idle: 6ms
    buffer_size: 2kb

dallas:
  pin: GPIO32
  update_interval: 5s

script:
  - id: update_pool_temperature_await
    mode: single
    then:
      - delay:
          minutes: 5
