substitutions:
  # Capacidad del tanque
  tanque_lleno_l: "550"
  # Litros cuando el flotador activa
  tanque_flotador_cargando: "375"
  # Litros cuando el flotador desactiva
  tanque_flotador_descargando: "60"
  device_name: eh-planta-alta
  friendly_name: Planta Alta

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml

globals:
  - id: tank_liters
    type: float
    initial_value: "0.0"
    restore_value: True

external_components:
  - source: github://glmnet/esphome@ape-external-component
    components: [arduino_port_expander]

i2c:

arduino_port_expander:
  - id: ape1
    address: 0x08
  - id: ape2
    address: 0x09

binary_sensor:
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 6
      mode:
        input: true
        pullup: true
    name: "Switch Escalera 1"
    internal: true
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_escalera
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 8
      mode:
        input: true
        pullup: true
    name: "Switch Escalera Hall"
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 4
      mode:
        input: true
        pullup: true
    name: "Switch Ante Baño 1"
    internal: true
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_ante_banio_pa
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 7
      mode:
        input: true
        pullup: true
    name: "Switch Ante Baño 2"
    internal: true
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_ante_banio_pa
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 3
      mode:
        input: true
        pullup: true
    name: "Switch Baño"
    filters:
      - delayed_on_off: 100ms
    internal: true
    on_state:
      then:
        - light.toggle: luz_banio_pa
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 9
      mode:
        input: true
        pullup: true
    name: "Movimiento Baño"
    device_class: motion
    filters:
      - delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 5
      mode:
        input: true
        pullup: true
    name: "Movimiento Hall"
    device_class: motion
    filters:
      - delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 2
      mode:
        input: true
        pullup: true
    name: "Ventana Baño"
    device_class: window
    filters:
      - delayed_on_off: 100ms
  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 11
      mode:
        input: true
        pullup: true
    # name: "Tanque Agua Arriba Flotador Pide"
    id: tanque_arriba_flotador
    filters:
      - invert:
      - delayed_on_off: 2s
    on_press:
      - globals.set:
          id: tank_liters
          value: ${tanque_flotador_descargando}
    on_release:
      - globals.set:
          id: tank_liters
          value: ${tanque_flotador_cargando}

  - platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 10
      mode:
        input: true
        pullup: true
    # name: "Tanque Agua Arriba Lleno"
    id: top_tank_full
    filters:
      - invert:
    #   - delayed_on_off: 15s
    on_press:
      - globals.set:
          id: tank_liters
          value: ${tanque_lleno_l}
  - platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 8
      mode:
        input: true
        pullup: true
    # name: "Tanque agua arriba flujo en salida"
    id: water_flowing_down
    filters:
      delayed_on_off: 100ms
    on_release:
      if:
        condition:
          switch.is_on: pressure_pump
        then:
          switch.turn_off: pressure_pump

  # - platform: gpio
  #   pin:
  #     arduino_port_expander: ape1
  #     number: 9
  #     mode:
  #       input: true
  #       pullup: true
  #   #name: "Tuberia casa presurizada"

  - platform: status
    name: "Planta Alta Status"
    internal: True
    on_press:
      then:
        - script.execute: api_just_connected

  - platform: homeassistant
    name: "Switch Escalera 1 from HA"
    entity_id: binary_sensor.switch_escalera_1
    on_state:
      then:
        if:
          condition:
            not:
              script.is_running: api_just_connected
          then:
            - light.toggle: luz_escalera

  - platform: homeassistant
    # water pump used to raise water from low tank to upper
    entity_id: switch.bomba_elevadora
    id: bomba_tanque

  - platform: homeassistant
    entity_id: input_boolean.alarma_luces
    id: alarma_luces
    on_press:
      then:
        - light.turn_on:
            id: luz_ante_banio_pa
            effect: Strobe
        - light.turn_on:
            id: luz_banio_pa
            effect: Strobe
        - light.turn_on:
            id: luz_escalera
            effect: Strobe
        - light.turn_on:
            id: luz_hall_pa
            effect: Strobe
        - light.turn_on:
            id: luz_patio_este
            effect: Strobe
        - light.turn_on:
            id: luz_patio_oeste
            effect: Strobe
        - light.turn_on:
            id: luz_patio_proyectores_sureste
            effect: Strobe
    on_release:
      then:
        - light.turn_off: luz_ante_banio_pa
        - light.turn_off: luz_banio_pa
        - light.turn_off: luz_escalera
        - light.turn_off: luz_hall_pa
        - light.turn_off: luz_patio_este
        - light.turn_off: luz_patio_oeste
        - light.turn_off: luz_patio_proyectores_sureste

output:
  - id: gpio_relay_1 # Baño
    inverted: true
    platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 2
  - id: gpio_relay_2 # Escalera
    inverted: true
    platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 3
  - id: gpio_relay_3 # Ante Baño
    inverted: true
    platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 4
  - id: gpio_relay_4 #
    inverted: true
    platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 5
  - id: gpio_relay_5 # Comun Luz Patio
    inverted: true
    platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 10
  - id: gpio_relay_6 # Luz Patio Este
    inverted: true
    platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 11
  - id: gpio_relay_7 # Luz Patio Oeste
    inverted: true
    platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 12
  - id: gpio_relay_8 # Luz Patio SurEste
    inverted: true
    platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 6
  - id: gpio_pressure_pump # Pressure pump
    platform: gpio
    pin:
      arduino_port_expander: ape2
      number: 13

light:
  - platform: binary
    id: luz_banio_pa
    name: "Luz baño Planta alta"
    output: gpio_relay_1
    effects:
      - strobe:
  - platform: binary
    id: luz_escalera
    name: "Luz Escalera"
    output: gpio_relay_2
    effects:
      - strobe:
  - platform: binary
    id: luz_ante_banio_pa
    name: "Luz Ante baño Planta alta"
    output: gpio_relay_3
    effects:
      - strobe:
  - platform: binary
    id: luz_hall_pa
    # Not connected
    # name: "Luz Hall Planta alta"
    output: gpio_relay_4
    effects:
      - strobe:

  - platform: binary
    id: luz_patio_este
    #name: "Luz Patio Este"
    output: gpio_relay_6
    on_turn_on:
      script.execute: set_patio_lights_common
    on_turn_off:
      script.execute: set_patio_lights_common
    effects:
      - strobe:

  - platform: binary
    id: luz_patio_oeste
    # name: "Luz Patio Oeste"
    output: gpio_relay_7
    on_turn_on:
      script.execute: set_patio_lights_common
    on_turn_off:
      script.execute: set_patio_lights_common
    effects:
      - strobe:

  - platform: binary
    id: luz_patio_proyectores_sureste
    # name: "Patio Proyectores Sureste"
    output: gpio_relay_8
    on_turn_on:
      script.execute: set_patio_lights_common
    on_turn_off:
      script.execute: set_patio_lights_common
    effects:
      - strobe:

script:
  - id: set_patio_lights_common
    then:
      # set the common neutral wire relay for patio lights
      if:
        condition:
          or:
            - light.is_on: luz_patio_este
            - light.is_on: luz_patio_oeste
            - light.is_on: luz_patio_proyectores_sureste
        then:
          output.turn_on: gpio_relay_5
        else:
          output.turn_off: gpio_relay_5
  - id: api_just_connected
    then:
      - delay: 40s

switch:
  - platform: output
    output: gpio_pressure_pump
    #name: Bomba Presurizadora
    id: pressure_pump

  - platform: template
    restore_mode: ALWAYS_OFF
    optimistic: true
    #name: Presurizadora Automatico
    id: auto_pressure_pump_manual
    on_turn_off:
      - switch.turn_off: pressure_pump

  - platform: template
    #name: Presurizadora con luz baño
    optimistic: true
    id: auto_pressure_pump_with_light
    restore_mode: ALWAYS_ON

interval:
  - interval: 1s
    then:
      - if:
          condition:
            binary_sensor.is_on: top_tank_full
          then:
            lambda: |-
              float new_level = id(tank_liters);
              if (isnan(new_level))
                id(tank_liters) = ${tanque_lleno_l};
      - if:
          condition:
            binary_sensor.is_on: bomba_tanque
          # about 500 liters of water are pumped on 22 minutes so
          # about 0.38 liters every second are pumped into the tank
          then:
            - lambda: |-
                float new_level = id(tank_liters);
                if (isnan(new_level))
                  new_level = id(tanque_arriba_flotador).state ? 40.0 : ${tanque_flotador_cargando};

                new_level += 0.38;
                if (new_level > ${tanque_lleno_l})
                  new_level = ${tanque_lleno_l};
                if (new_level > ${tanque_flotador_cargando} && id(tanque_arriba_flotador).state)
                  new_level = ${tanque_flotador_cargando};
                id(tank_liters) = new_level;
      - if:
          condition:
            binary_sensor.is_on: water_flowing_down
          then:
            - lambda: |-
                float new_level = id(tank_liters);
                if (isnan(new_level))
                  new_level = id(tanque_arriba_flotador).state ? 40.0 : 450.00;

                if (id(pressure_pump).state)
                  new_level -= 0.16;
                else
                  new_level -= 0.07;

                if (new_level < 40 && !id(tanque_arriba_flotador).state)
                  new_level = 40;

                if (new_level < 0)
                  new_level = 0;

                id(tank_liters) = new_level;

  - interval: 100ms
    then:
      - if:
          condition:
            for:
              time: 15s
              condition:
                - not:
                    binary_sensor.is_on: water_flowing_down
                - switch.is_on: pressure_pump
          then:
            - switch.turn_off: pressure_pump
            - logger.log:
                level: WARN
                format: Apagando bomba, no hay flujo de agua

sensor:
  - platform: template
    #name: Nivel Tanque Arriba
    id: unused_sensor_id
    unit_of_measurement: liters
    lambda: return id(tank_liters);
#
# IO Table
## MW / UW Marked Wire / Unmarked Wire

# MW - White 0V
# MW - Red +12V

# APE2 06 Ribbon 3 Black - # MW - Yellow - Int Escalera 1
# APE2 08 Ribbon 3 Purple - # UW - White - Int Escalera 2
# APE2 04 Ribbon 3 Blue - # UW - Yellow - Int Ante Baño 1
# APE2 07 Ribbon 3 Green - # UW - Red - Int Ante Baño 2
# APE2 03 Ribbon 3 Yellow - # UW - Blue Int Baño
# APE2 09 Ribbon 3 White - # MW - Blue - PIR Baño
# APE2 05 Ribbon 3 Gray - # MW - Marron - PIR Hall
# APE2 02 Ribbon 3 Red - # UW - Marron - Alarma Ventana Hall
# APE2 12 Ribbon 3 Brown -
# APE2 13 Ribbon 3 Orange - Pressure pump

# APE2 11 Ribbon 2 White - Tanque 1 - Azul - Flotador
# APE2 10 Ribbon 2 Purple - Tanque 2 - Verde - Reed switch lleno - Normally open

# APE1 07 Ribbon 2 Green -
# APE1 08 Ribbon 2 Orange - Tanque 4 - Naranja - Red - Water flow Sensor
# APE1 09 Ribbon 2 Brown - Tanque 5 - Blanco Naranja - Blue - Pipe pressurized

# APE1 A0 Ribbon 1 Black - Tanque 6 - Marron
# APE1 A1 Ribbon 1 Purple - Tanque 7 - Blanco - Marron
# APE1 A2 Ribbon 1 Green
# APE1 13 Ribbon 1 White
