substitutions:
  device_name: eh-porton
  friendly_name: Porton

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml
 
external_components:
  source: github://glmnet/esphome-components
  components: [arduino_port_expander]
  
i2c:

arduino_port_expander:
  id: ape

output:
  - platform: gpio
    id: ape_relay_1
    pin:
      arduino_port_expander: ape
      number: 4

button:
  - platform: output
    duration: 1s
    output: ape_relay_1
    name: "Porton boton"
    id: porton_boton

binary_sensor:
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 2
      mode:
        input: true
        pullup: true
    name: Porton
    device_class: garage_door
    filters:
      delayed_on_off: 2s
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 3
      mode:
        input: true
        pullup: true
    name: Movimiento garage
    device_class: motion
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 5
      mode:
        input: true
        pullup: true
    name: Barrera porton garage
    device_class: safety
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 14
      mode:
        input: true
        pullup: true
    name: Porton movimiento
    device_class: moving
    filters:
      - invert:
  - platform: gpio
    pin:
      arduino_port_expander: ape
      number: 15
      mode:
        input: true
        pullup: true
    name: Porton Manual
    device_class: garage_door
    filters:
      - delayed_on_off: 2s

# Ribbon:
# Black: VCC 3.3V
# White: GND 0V
# Gray: Arduino A2
# Violet: Arduino 5 - > Barrera porton garage
# Blue: Arduino A1 -> Porton Reed switch lado puerta
# Green: Arduino 3 -> Movimiento garage
# Yellow: Arduino A0 -> Porton moviendo
# Orange: Arduino 2 -> Porton Reed switch lado vecino

