substitutions:
  device_name: eh-pa-hall
  friendly_name: Planta Alta Hall

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp32.idf.yaml

i2c:
  scl: GPIO13
  sda: GPIO14
  scan: true

status_led:
  pin: GPIO12

sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    bus_voltage:
      name: "${friendly_name} Voltage"
    max_voltage: 32.0V
    max_current: 3.2A
    update_interval: 60s

output:
  - platform: gpio
    pin: GPIO16
    id: relay_4
    inverted: true
  - platform: gpio
    pin: GPIO32
    id: relay_3
    inverted: true
  - platform: gpio
    pin: GPIO4
    id: relay_2
    inverted: true
  - platform: gpio
    pin: GPIO5
    id: relay_1
    inverted: true

mcp23017:
  - id: mcp_base

binary_sensor:
  - platform: gpio
    internal: true
    name: Switch Escalera 1
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_escalera
    pin:
      mcp23xxx: mcp_base
      number: 1
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: Switch Escalera Hall
    filters:
      - delayed_on_off: 100ms
    pin:
      mcp23xxx: mcp_base
      number: 3
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: Switch Ante Baño N
    internal: true
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_ante_banio_pa
    pin:
      mcp23xxx: mcp_base
      number: 5
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: Switch Ante Baño S 1
    internal: true
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - light.toggle: luz_ante_banio_pa
    pin:
      mcp23xxx: mcp_base
      number: 7
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: Switch Ante Baño S 2
    filters:
      - delayed_on_off: 100ms
    pin:
      mcp23xxx: mcp_base
      number: 9
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: Switch Baño
    filters:
      - delayed_on_off: 100ms
    internal: true
    on_state:
      then:
        - light.toggle: luz_banio_pa
    pin:
      mcp23xxx: mcp_base
      number: 11
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: input_7
    internal: true #spare
    pin:
      mcp23xxx: mcp_base
      number: 13
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Movimiento Hall"
    device_class: motion
    filters:
      - delayed_on_off: 100ms
    pin:
      mcp23xxx: mcp_base
      number: 15
      mode:
        input: true
        pullup: true

switch:
  - platform: output
    id: rgb_lights_power
    name: "Planta Alta Fuente RGB"
    output: relay_1

light:
  - platform: binary
    id: luz_escalera
    name: "Luz Escalera"
    output: relay_2
    effects:
      - strobe:
  - platform: binary
    id: luz_ante_banio_pa
    name: "Luz Ante baño Planta alta"
    output: relay_3
    effects:
      - strobe:
  - platform: binary
    id: luz_banio_pa
    # Not connected
    name: "Luz baño Planta alta"
    output: relay_4
