substitutions:
  device_name: eh-pool-ionizer
  friendly_name: Ionizador

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml

esp8266:
  board: nodemcuv2

output:
  - platform: gpio
    pin: D0
    id: output_d0
  - platform: gpio
    pin: D4
    id: output_d4

switch:
  - platform: template
    name: Ionizador
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: True
    id: ionizer_switch
    on_turn_off:
      then:
        - output.turn_off: output_d0
        - output.turn_off: output_d4

interval:
  - interval: 600s # set the delay below to half this value
    then:
      - if:
          condition:
            - switch.is_on: ionizer_switch
          then:
            - output.turn_on: output_d0
            - output.turn_off: output_d4
            - delay: 300s
            - output.turn_off: output_d0
            - output.turn_on: output_d4
          else:
            - output.turn_off: output_d0
            - output.turn_off: output_d4
