substitutions:
  device_name: Quincho interruptores puerta

esphome:
  name: eh-quincho-puerta

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
api:

ota:

sensor:
  - platform: uptime
    name: ${device_name} uptime
  - platform: wifi_signal
    name: ${device_name} signal

button:
  - platform: restart
    name: ${device_name} restart

text_sensor:
  - platform: wifi_info
    bssid:
      name: ${device_name} BSSID

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  power_save_mode: NONE


logger:
  level: DEBUG

binary_sensor:
  - platform: status
    name: "${device_name} Status"

  - platform: gpio
    pin:
      mode:
        input: True
        pullup: True
      inverted: True
      number: GPIO23
    name: Switch 1 puerta quincho

  - platform: gpio
    pin:
      mode:
        input: True
        pullup: True
      inverted: True
      number: GPIO22
    name: Switch 2 puerta quincho

  - platform: gpio
    pin:
      mode:
        input: True
        pullup: True
      inverted: True
      number: GPIO21
    name: Switch 3 puerta quincho

  - platform: gpio
    pin:
      mode:
        input: True
        pullup: True
      inverted: True
      number: GPIO18
    name: Timbre quincho

  - platform: gpio
    pin:
      mode:
        input: True
      inverted: True
      number: GPIO5
    device_class: door
    name: Puerta frente quincho

status_led:
  pin: GPIO2
