substitutions:
  device_name: eh-quincho
  friendly_name: Quincho

packages:
  board: !include .pkg.esp32.idf.yaml
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml

output:
  - platform: gpio
    pin: GPIO13
    id: relay1
    inverted: true
  - platform: gpio
    pin: GPIO16
    id: relay2
    inverted: true
  - platform: gpio
    pin: GPIO32
    id: relay3
    inverted: true
  - platform: gpio
    pin: GPIO14
    id: relay4
    inverted: true

light:
  - platform: binary
    output: relay1
    name: Luz Quincho SO
  - platform: binary
    output: relay2
    name: Luz Quincho NE

binary_sensor:
  - platform: gpio
    pin: GPIO33 #1
    name: Puerta quincho parrilla
    filters:
      - invert:
    device_class: door
  - platform: gpio
    pin: GPIO39 #2
    name: Puerta quincho sala
    filters:
      - invert:
    device_class: door
  - platform: gpio
    pin:
      number: GPIO35
      inverted: True
    name: spare_gpio3
    internal: true
  - platform: gpio
    pin: GPIO36
    name: spare_gpio4
    internal: true

switch:
  - platform: output
    name: Quincho Parlantes
    id: switch_quincho_parlantes
    output: relay3
