substitutions:
  device_name: eh-quincho-puerta
  friendly_name: Quincho interruptores puerta

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp32.idf.yaml
  

wifi:
  power_save_mode: NONE

binary_sensor:
  - platform: gpio
    pin:
      mode:
        input: True
        pullup: True
      inverted: True
      number: GPIO23
    name: Switch 1 puerta quincho

  - platform: gpio
    pin:
      mode:
        input: True
        pullup: True
      inverted: True
      number: GPIO22
    name: Switch 2 puerta quincho

  - platform: gpio
    pin:
      mode:
        input: True
        pullup: True
      inverted: True
      number: GPIO21
    name: Switch 3 puerta quincho

  - platform: gpio
    pin:
      mode:
        input: True
        pullup: True
      inverted: True
      number: GPIO18
    name: Timbre quincho

  - platform: gpio
    pin:
      mode:
        input: True
      inverted: True
      number: GPIO5
    device_class: door
    name: Puerta frente quincho

status_led:
  pin: GPIO2
