substitutions:
  device_name: eh-termotanque
  friendly_name: Termotanque casa

packages:
  home: !include .pkg.home.yaml
  wifi: !include .pkg.wifi.yaml
  board: !include .pkg.esp8266.yaml
  
logger:
  baud_rate: 0 # use UART pins for IO

output:
  - platform: gpio
    id: rly1
    pin: GPIO13

switch:
  - platform: output
    name: "Encendido termotanque casa"
    id: switchBoiler
    output: rly1

binary_sensor:
  - platform: template
    name: Calentando termotanque casa
    id: boiler_heating

dallas:
  - pin: GPIO5

sensor:
  - platform: dallas
    name: Temperatura termotanque casa
    address: 0xf176c32712646128
    id: temperature_sensor
  - platform: adc
    pin: A0
    id: ldr
    name: LDR Termotanque casa
    entity_category: diagnostic
    update_interval: 10s
    on_value:
      then:
        - lambda: |-
            id(boiler_heating).publish_state(x < 0.2);

climate:
  - platform: thermostat
    name: Termotanque casa
    sensor: temperature_sensor
    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: switchBoiler
    idle_action:
      - switch.turn_off: switchBoiler
    heat_deadband: 1
    heat_overrun: 1
    visual:
      max_temperature: 60
      min_temperature: 10
      temperature_step: 1
    icon: mdi:water-boiler
    default_preset: Normal
    preset:
      - name: Normal
        default_target_temperature_low: 45
        mode: HEAT
      - name: Eco
        default_target_temperature_low: 30
        mode: HEAT

