---
esphome:
  name: eh-termotanque

esp8266:
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

logger:
  level: DEBUG
  baud_rate: 0 # use UART pins for IO

output:
  - platform: gpio
    id: rly1
    pin:
      number: GPIO13

switch:
  - platform: output
    name: "Encendido termotanque casa"
    id: switchBoiler
    output: rly1
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: template
    name: Calentando termotanque casa
    id: boiler_heating

dallas:
  - pin: GPIO5

sensor:
  - platform: dallas
    name: Temperatura termotanque casa
    address: 0xf176c32712646128
  - platform: adc
    pin: A0
    name: LDR Termotanque casa
    entity_category: diagnostic
    update_interval: 10s
    on_value:
      then:
        - lambda: |-
            id(boiler_heating).publish_state(x < 0.2);

