esphome:
  name: eh_cerco
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

logger:
  baud_rate: 0 # using pins for IO
  level: VERBOSE

sensor:
  - platform: adc
    pin: A0
    name: "Bateria Cerco"
    update_interval: 60s
    filters:
      # 12.61V = 0.825195
      # 10.26 -> 0.6767
      # 12.78 -> 0.8457
      # formula: 12.78 / 0.8457 = multiply
      - multiply: 15.135

binary_sensor:
  - platform: status
    name: "Cerco Status"
  - platform: gpio
    pin:
      number: GPIO3 #RX
      mode: INPUT_PULLUP
    filters:
      - invert:
      - delayed_off: 2s # pulses every second
    id: pulse
    name: Activado

  - platform: gpio
    pin:
      number: GPIO1 #TX
      mode: INPUT_PULLUP
    id: alarm # green
    name: " Alarma Cerco"
    filters:
      - invert:
  - platform: gpio
    pin:
      number: GPIO4
    id: line
    device_class: power
    name: "Linea AC Cerco"



  # brown +12v bat
  # white brown 0v
  # blue pulse
  # green alarm C
  # white orange alarm NO
  # orange line