esphome:
  name: eh_cocina
  platform: ESP8266
  board: nodemcu
  # Use a local copy of ESPHome
  includes:
    - arduino_port_expander.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

i2c:
  id: i2c_component

logger:
  level: DEBUG


custom_component:
- id: ape
  lambda: |-
    auto ape_component = new ArduinoPortExtender(i2c_component, 0x08);
    return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 7),
            ape_binary_output(ape, 6),
            ape_binary_output(ape, 5),
            ape_binary_output(ape, 4)};
  outputs:
    - id: gpio_relay_1
      inverted: true
    - id: gpio_relay_2
      inverted: true
    - id: gpio_relay_3
      inverted: true
    - id: gpio_relay_4
      inverted: true

light:
  - platform: binary
    id: luz_cocina
    name: "Luz cocina"
    output: gpio_relay_1
  - platform: binary
    id: luz_mesa_cocina
    name: "Luz mesa cocina"
    output: gpio_relay_2
  - platform: binary
    id: luz_exterior_pasillo
    name: "Luz exterior pasillo"
    output: gpio_relay_3

binary_sensor:
  - platform: status
    name: "Cocina Status"
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 2), // ribbon purple
              ape_binary_sensor(ape, 3), // ribbon white
              ape_binary_sensor(ape, 8), // ribbon verde
              ape_binary_sensor(ape, 15), // A1 ribbon orange
              ape_binary_sensor(ape, 14)}; // ribbon red
    binary_sensors:
      - name: "Switch Cocina puerta 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_cocina
      - name: "Switch Cocina puerta 2"
        internal: true
        on_state:
          then:
            - light.toggle: luz_mesa_cocina
      - name: "Switch Cocina puerta 3"
        internal: true
        on_state:
          then:
            - light.toggle: luz_exterior_pasillo
      - name: "Switch Mesa cocina"
        internal: true
        on_state:
          then:
            - light.toggle: luz_mesa_cocina
      - name: "Ventana cocina"
        device_class: window
