esphome:
  name: eh_comedor_window
  platform: ESP8266
  board: nodemcu
  esp8266_restore_from_flash: yes

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

logger:
  level: VERBOSE

globals:
  - id: tilt_pos
    type: float

servo:
  - output: "ob_t"
    id: ob_tilt
    restore: true
    min_level: 3%
    max_level: 12%
    run_duration: 3s
    keep_on_time: 2s

output:
  - platform: esp8266_pwm ## this is for the servo
    id: "ob_t"
    pin: D0
    frequency: 50 Hz

cover:
  - platform: template
    name: Persiana comedor
    tilt_lambda: |-
      return id(tilt_pos);
    tilt_action:
      - lambda: |-
          id(ob_tilt).write((1 - tilt) * 2 - 1);
          id(tilt_pos) = tilt;

binary_sensor:
  - platform: status
    name: "Comedor Ventana Status"
