esphome:
  name: eh-dor-sur
  platform: ESP8266
  board: nodemcu
  # Use a local copy of ESPHome
  includes:
    - arduino_port_expander.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:


ota:

i2c:
  id: i2ccomponent

logger:
  level: DEBUG

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExpander(i2ccomponent, 0x08);
      return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 7),
            ape_binary_output(ape, 6),
            ape_binary_output(ape, 5)};
  outputs:
    - id: gpio_relay_1
      inverted: true
    - id: gpio_relay_2
      inverted: true
    - id: gpio_relay_3
      inverted: true

light:
  - platform: binary
    id: luz_dormitorio_sur
    name: "Dormitorio Sur"
    output: gpio_relay_1
  - platform: binary
    id: luz_dormitorio_sur_cama_pared
    name: "Dormitorio Sur Cama Pared"
    output: gpio_relay_2
  - platform: binary
    id: luz_dormitorio_sur_cama_ventana
    name: "Dormitorio Sur Cama Ventana"
    output: gpio_relay_3


binary_sensor:
  - platform: status
    name: "Dormitorio Sur Status"
  - platform: homeassistant
    id: colors_led_feedback
    entity_id: light.dormitorio_sur_rgb

  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 2), // ribbon purple
              ape_binary_sensor(ape, 16), // ribbon white
              ape_binary_sensor(ape, 8), // ribbon verde
              ape_binary_sensor(ape, 1),
              ape_binary_sensor(ape, 0),
              ape_binary_sensor(ape, 10), //  "Cama Ventana Arriba"
              ape_binary_sensor(ape, 9), // "Cama Ventana Abajo"
              ape_binary_sensor(ape, 14)}; // ribbon red
    binary_sensors:
      - name: "Switch Puerta 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_sur
      - name: "Switch puerta 2"
        internal: true
        on_state:
          then:
            if:
              condition:
                or:
                  - light.is_on: luz_dormitorio_sur_cama_ventana
                  - light.is_on: luz_dormitorio_sur_cama_pared
              then:
                - light.turn_off: luz_dormitorio_sur_cama_ventana
                - light.turn_off: luz_dormitorio_sur_cama_pared
              else:
                - light.turn_on: luz_dormitorio_sur_cama_ventana
                - light.turn_on: luz_dormitorio_sur_cama_pared
      - name: "Switch puerta sur"
      - name: "Switch Cama Pared 1" # Enciende luces
        internal: true
        on_state:
            then:
              - if:
                  condition:
                    binary_sensor.is_off: colors_led_feedback
                  then:
                    script.execute: color_leds_lights_on
                  else:
                    if:
                      condition:
                        light.is_off: luz_dormitorio_sur_cama_pared
                      then:
                        light.turn_on: luz_dormitorio_sur_cama_pared
                      else:
                        if:
                          condition:
                            light.is_off: luz_dormitorio_sur
                          then:
                            light.turn_on: luz_dormitorio_sur
                          else:
                            light.turn_on: luz_dormitorio_sur_cama_ventana

      - name: "Switch Cama Pared 2" # Apaga luces
        internal: true
        on_state:
            then:
              - if:
                  condition:
                    light.is_on: luz_dormitorio_sur
                  then:
                    light.turn_off: luz_dormitorio_sur
                  else:
                    if:
                      condition:
                        light.is_on: luz_dormitorio_sur_cama_pared
                      then:
                        light.turn_off: luz_dormitorio_sur_cama_pared
                      else:
                        if:
                          condition:
                            binary_sensor.is_on: colors_led_feedback
                          then:
                            script.execute: color_leds_lights_off
                          else:
                            light.turn_off: luz_dormitorio_sur_cama_ventana
      - name: "Switch Cama Ventana 1" # Enciende luces
        internal: true
        on_state:
            then:
              - if:
                  condition:
                    binary_sensor.is_off: colors_led_feedback
                  then:
                    script.execute: color_leds_lights_on
                  else:
                    if:
                      condition:
                        light.is_off: luz_dormitorio_sur_cama_ventana
                      then:
                        light.turn_on: luz_dormitorio_sur_cama_ventana
                      else:
                        if:
                          condition:
                            light.is_off: luz_dormitorio_sur
                          then:
                            light.turn_on: luz_dormitorio_sur
                          else:
                            light.turn_on: luz_dormitorio_sur_cama_pared

      - name: "Switch Cama Ventana 2"
        internal: true
        on_state:
            then:
              - if:
                  condition:
                    light.is_on: luz_dormitorio_sur
                  then:
                    light.turn_off: luz_dormitorio_sur
                  else:
                    if:
                      condition:
                        light.is_on: luz_dormitorio_sur_cama_ventana
                      then:
                        light.turn_off: luz_dormitorio_sur_cama_ventana
                      else:
                        if:
                          condition:
                            binary_sensor.is_on: colors_led_feedback
                          then:
                            script.execute: color_leds_lights_off
                          else:
                            light.turn_off: luz_dormitorio_sur_cama_pared

      - name: "Ventana Dormitorio Sur"
        device_class: window

switch:
  - platform: restart
    name: "Dormitorio Sur Restart"

script:
  - id: color_leds_lights_on
    then:
      homeassistant.service:
        service: light.turn_on
        data:
          entity_id: light.dormitorio_sur_rgb

  - id: color_leds_lights_off
    then:
      homeassistant.service:
        service: light.turn_off
        data:
          entity_id: light.dormitorio_sur_rgb

