esphome:
  name: eh_dor_este
  platform: ESP8266
  board: nodemcu
  includes:
    - arduino_port_expander.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

i2c:
  id: i2ccomponent

logger:
  level: DEBUG

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
      return {ape_component};

output:
  - platform: custom
    type: binary
    lambda: |-
      return {ape_binary_output(ape, 7),
              ape_binary_output(ape, 6)};
    outputs:
      - id: gpio_relay_1
        inverted: true
      - id: gpio_relay_2
        inverted: true

light:
  - platform: binary
    id: luz_dormitorio_este
    name: "Dormitorio Este"
    output: gpio_relay_1
  - platform: binary
    id: luz_dormitorio_este_cama
    name: "Dormitorio Este Cama"
    output: gpio_relay_2

binary_sensor:
  - platform: status
    name: "Dormitorio Este Status"
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 15), // A1 ribbon orange
              ape_binary_sensor(ape, 3), // ribbon white
              ape_binary_sensor(ape, 8), // ribbon green
              ape_binary_sensor(ape, 2), // ribbon purple
              ape_binary_sensor(ape, 14)}; // A0 ribbon red
    binary_sensors:
      - name: "Switch Puerta 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_este
      - name: "Switch puerta 2"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_este_cama
      - name: "Switch Cama 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_este
      - name: "Switch Cama 2"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_este_cama
      - name: "Ventana Dormitorio Este"
        device_class: window

switch:
  - platform: restart
    name: "Dormitorio Este Restart"
