esphome:
  name: eh_dor_nor
  platform: ESP8266
  board: nodemcu
  includes:
    - arduino_port_expander.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:

i2c:
  id: i2ccomponent

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExpander(i2ccomponent, 0x08);
      return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 7),
            ape_binary_output(ape, 6),
            ape_binary_output(ape, 5)};
  outputs:
    - id: gpio_relay_1
      inverted: true
    - id: gpio_relay_2
      inverted: true
    - id: gpio_relay_3
      inverted: true


light:
  - platform: binary
    id: techo
    name: "Dormitorio Norte Techo"
    output: gpio_relay_1
  - platform: binary
    id: cama_pared
    name: "Dormitorio Norte Cama Pared"
    output: gpio_relay_2
  - platform: binary
    id: cama_ventana
    name: "Dormitorio Norte Cama Ventana"
    output: gpio_relay_3

binary_sensor:
  - platform: status
    name: "Dormitorio Norte Status"
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 2), // A1 ribbon orange
              ape_binary_sensor(ape, 3), // ribbon white
              ape_binary_sensor(ape, 8), // ribbon green
              ape_binary_sensor(ape, 0),
              ape_binary_sensor(ape, 1),
              ape_binary_sensor(ape, 9),
              ape_binary_sensor(ape, 10),
              ape_binary_sensor(ape, 14)};
    binary_sensors:
      - name: "Dormitorio norte Switch puerta 1"
        internal: true
        on_state:
          then:
            - light.toggle: techo
      - name: "Dormitorio norte Switch puerta 2"
        internal: true
        on_state:
          then:
            if:
              condition:
                or:
                  - light.is_on: cama_ventana
                  - light.is_on: cama_pared
              then:
                - light.turn_off: cama_ventana
                - light.turn_off: cama_pared
              else:
                - light.turn_on: cama_ventana
                - light.turn_on: cama_pared
      - name: "Dormitorio norte Switch puerta"
      - name: "Dormitorio norte Switch cama pared 1"
        internal: true
        on_state:
          then:
            - light.toggle: cama_pared
      - name: "Dormitorio norte Switch cama pared 2"
        internal: true
        on_state:
          then:
            - light.toggle: techo
      - name: "Dormitorio norte Switch cama ventana 1"
        internal: true
        on_state:
          then:
            - light.toggle: cama_ventana
      - name: "Dormitorio norte Switch cama ventana 2"
        internal: true
        on_state:
          then:
            - light.toggle: techo
      - name: "Dormitorio norte Ventana"
        device_class: window

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%

climate:
  platform: coolix
  name: 'AC Dormitorio Norte'