esphome:
  name: eh-dor-nor
  platform: ESP8266
  board: nodemcu
  includes:
    - arduino_port_expander.h
  on_boot:
    - switch.turn_on: tomas_electricos

substitutions:
  entity_prefix: "Dormitorio Norte"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:

i2c:
  id: i2ccomponent

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExpander(i2ccomponent, 0x08);
      return {ape_component};

output:
  - platform: custom
    type: binary
    lambda: |-
      return {ape_binary_output(ape, 7),
              ape_binary_output(ape, 6),
              ape_binary_output(ape, 5),
              ape_binary_output(ape, 4)};
    outputs:
      - id: gpio_relay_1
        inverted: true
      - id: gpio_relay_2
        inverted: true
      - id: gpio_relay_3
        inverted: true
      - id: gpio_relay_4

light:
  - platform: binary
    id: techo
    name: "${entity_prefix} luz techo"
    output: gpio_relay_1
  - platform: binary
    id: cama_pared
    name: "${entity_prefix} luz cama pared"
    output: gpio_relay_2
  - platform: binary
    id: cama_ventana
    name: "${entity_prefix} luz cama ventana"
    output: gpio_relay_3

switch:
  - platform: output
    output: gpio_relay_4
    id: tomas_electricos
    name: "${entity_prefix} tomas electricos"



binary_sensor:
  - platform: status
    name: "${entity_prefix} status"
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 2),
              ape_binary_sensor(ape, 3),
              ape_binary_sensor(ape, 8),
              ape_binary_sensor(ape, 11),
              ape_binary_sensor(ape, 12),
              ape_binary_sensor(ape, 14),
              ape_binary_sensor(ape, 15),
              ape_binary_sensor(ape, 9)};
    binary_sensors:
      - name: "${entity_prefix} switch puerta 1"
        filters:
          delayed_on_off: 100ms
        on_state:
          then:
            - light.toggle: techo
      - name: "${entity_prefix} switch puerta 2"
        filters:
          delayed_on_off: 200ms
        on_state:
          then:
            if:
              condition:
                or:
                  - light.is_on: cama_ventana
                  - light.is_on: cama_pared
              then:
                - light.turn_off: cama_ventana
                - light.turn_off: cama_pared
              else:
                - light.turn_on: cama_ventana
                - light.turn_on: cama_pared
      - name: "${entity_prefix} switch puerta 3"
        filters:
          delayed_on_off: 100ms
      - name: "${entity_prefix} switch cama pared 1"
        filters:
          delayed_on_off: 100ms
        on_state:
          then:
            - light.toggle: cama_pared
      - name: "${entity_prefix} switch cama pared 2"
        filters:
          delayed_on_off: 100ms
        on_state:
          then:
            - light.toggle: techo
      - name: "${entity_prefix} switch cama ventana 1"
        filters:
          delayed_on_off: 100ms
        on_state:
          then:
            - light.toggle: cama_ventana
      - name: "${entity_prefix} switch cama ventana 2"
        filters:
          delayed_on_off: 100ms
        on_state:
          then:
            - light.toggle: techo
      - name: "${entity_prefix} ventana"
        filters:
          delayed_on_off: 100ms
        device_class: window

remote_transmitter:
  pin: GPIO14 # ribbon gray
  carrier_duty_percent: 50%

# New board pinout:

# ESP                     Female Header
#                           11  12        PS
# 0 RX   Arduino            13  14        PS
# 1 TX                      15  16        PS
#                           17  18        PS
#          Male header
#  10 pin: 2 4 6 8 10
#          1 3 5 7 9
#

# RX:
# TX:

#    RIBBON        PIN
# 1: black        +12 V in
# 2: white        APE 3            switch puerta 2
# 3: gray         GPIO12
# 4: purple       APE 2            switch puerta 1
# 5: blue         GPIO13
# 6: green        APE 8            switch puerta 3
# 7: yellow   ->  GROUND
# 8: orange       APE A1           switch cama ventana 2
# 9: red          APE A0           switch cama ventana 1
# 10: brown       +5V


# 11 GND
# 12 3.3V
# 13 APE 9                         reed switch ventana
# 14 APE 10                        reed switch puerta
# 15 APE 13                        pir
# 16 APE 11                        switch cama pared 1
# 17 APE 12                        switch cama pared 2
# 18

