esphome:
  name: eh_estudio
  platform: ESP8266
  board: nodemcu
  includes:
    - arduino_port_expander.h
  on_boot:
    then:
    - fan.turn_off: extractor_banio

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

i2c:
  id: i2c_component

logger:
  level: VERBOSE

custom_component:
- id: ape
  lambda: |-
    auto ape_component = new ArduinoPortExpander(id(i2c_component), 0x08);
    return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(id(ape), 7),
            ape_binary_output(id(ape), 6),
            ape_binary_output(id(ape), 5),
            ape_binary_output(id(ape), 4)};
  outputs:
  - id: gpio_relay_1
    inverted: true
  - id: gpio_relay_2
    inverted: true
  - id: gpio_relay_3
    inverted: true
  - id: gpio_relay_4
    inverted: true

light:
- platform: binary
  id: luz_estudio
  name: "Luz estudio"
  output: gpio_relay_1
- platform: binary
  id: luz_pasillo
  name: "Luz pasillo"
  output: gpio_relay_2
- platform: binary
  id: luz_banio
  name: "Luz baño"
  output: gpio_relay_3

fan:
- platform: binary
  id: extractor_banio
  output: gpio_relay_4
  name: "Extractor baño"

switch:
- platform: restart
  name: "Estudio Restart"

binary_sensor:
- platform: status
  name: "Estudio Status"
- platform: custom
  lambda: |-
    return {ape_binary_sensor(id(ape), 14 + 3),
            ape_binary_sensor(id(ape), 2),
            ape_binary_sensor(id(ape), 14 + 2),
            ape_binary_sensor(id(ape), 8),
            ape_binary_sensor(id(ape), 14 + 1),
            ape_binary_sensor(id(ape), 12),
            ape_binary_sensor(id(ape), 10),
            ape_binary_sensor(id(ape), 9),
            ape_binary_sensor(id(ape), 13),
            ape_binary_sensor(id(ape), 11),
            ape_binary_sensor(id(ape), 14 + 0),
            ape_binary_sensor(id(ape), 3)};
  binary_sensors:
  - name: "Switch estudio puerta 1" # A3
    internal: true
    on_state:
      then:
      - light.toggle: luz_estudio
  - name: "Switch estudio puerta 2" # DI2
    internal: true
    on_state:
      then:
      - light.toggle: luz_pasillo
  - name: "Switch estudio galeria 1" # A2
    internal: true
    filters:
      delayed_on_off: 100ms
    on_state:
    - light.toggle: luz_estudio
  - name: "Switch Estudio Galeria" # DI8
  - name: "Switch Estudio Patio" # A1
  - name: "Ventana Comedor Norte" # DI12
    device_class: window
  - name: "Switch escalera 1" # DI10
  - name: "Switch escalera 2" # DI9
  - name: "Switch baño 1" # DI13
    filters:
    - delayed_on: 50ms
    - delayed_off: 50ms
    on_state:
      then:
      - light.toggle: luz_banio
      - script.execute: keep_banio_light
  - name: "Switch baño 2" # DI11
    on_state:
      then:
      - if:
          condition:
            lambda: return id(extractor_banio).state;
          then:
            - script.execute: auto_off_extractor
  - name: "Movimiento estudio" # A0
    device_class: motion
  - name: "Puerta Baño" # DI3
    id: puerta_banio
    device_class: door
    filters:
    - delayed_on: 100ms
    - delayed_off: 100ms
    on_state: # Open or close door
      then:
      - script.execute: auto_off_extractor
      - if:
          condition:
            light.is_on: luz_banio
          then:
            script.execute: auto_off_luz_banio

    on_press: # Open door
      then:
      - if:
          condition:
            not:
              script.is_running: keep_banio_light
          then:
            - script.execute: auto_off_luz_banio


script:
  - id: keep_banio_light
    mode: restart
    then:
      - delay: 5s

  - id: auto_off_luz_banio
    mode: restart
    then:
      - light.turn_on: luz_banio
      - if:
          condition:
            binary_sensor.is_on: puerta_banio # open
          then:
            - delay: 5 min
          else:
            - delay: 10 min
      - light.turn_off: luz_banio

  - id: auto_off_extractor
    mode: restart
    then:
      - fan.turn_on: extractor_banio
      - logger.log: Stopping fan in 10 minutes
      - delay: 10 min
      - fan.turn_off: extractor_banio


###
# module info:
# Male Header:
# GND - White | DI2 - Pur |  DI8 - Greeen |  NC       | A2 Brown
# 12V - Black | A1 - Gray |  5V -    Blue |  A0 - Yel | A3 Red


# Female Header
# GND  |  3.3V
# DI9  |  DI10  -> puintos escalera
# DI13 |  DI11  -> puntos baño
# DI12 |  DI3  ->  DI12 Ventana, DI3 Puerta baño (Rojo)

# Cables entre estudio - baño
# Cable 1
# Blanco - GND
# Azul   - 12V          -
# Marron - IR LED       - GPIO14
# Amaril - PIR          - r Yell
# Rojo   - Puerta SW 1  - r Red
# Cable 2
# Blanco - 5V LED
# Rojo   - Puerta SW 2  - r Purple
# Marron - Galeria SW 1 - r Green
# Amaril - Galeria SW 2 - r Brown
# Azul   - Galeria SW 3 - r Gray

# cable baño
# rojo: Puerta
# blanco: 0V
# marron: DHT Data
# azul: 5V

