esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

logger:
  level: debug

api:
ota:

# sensor:
#   - platform: wifi_signal
#     name: "WiFi Signal h801light"
#     update_interval: 60s

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  # - platform: esp8266_pwm
  #   pin: 14
  #   frequency: 1000 Hz
  #   id: pwm_w1
  # - platform: esp8266_pwm
  #   pin: 4
  #   frequency: 1000 Hz
  #   id: pwm_w2
  # - platform: esp8266_pwm
  #   id: output_pin5
  #   frequency: 1000 Hz
  #   inverted: true
  #   pin: 5
  # - platform: esp8266_pwm
  #   id: output_pin1
  #   inverted: true
  #   frequency: 1000 Hz
  #   pin: 1

light:
  - platform: rgb
    name: $light_name
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    effects:
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s

      - strobe:
          name: Mario
          colors:
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
            - state: True
              brightness: 100%
              red: 0%
              green: 0%
              blue: 100%
              duration: 500ms
            - state: True
              brightness: 100%
              red: 100%
              green: 100%
              blue: 0%
              duration: 500ms
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
      - strobe:
          name: Birthday
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 150ms
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: True
              brightness: 100%
              red: 00%
              green: 0%
              blue: 100%
              duration: 500ms
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: True
              brightness: 100%
              red: 00%
              green: 0%
              blue: 100%
              duration: 500ms
            - state: True
              brightness: 100%
              red: 100%
              green: 10%
              blue: 50%
              duration: 2500ms
            - state: True
              brightness: 100%
              red: 40%
              green: 40%
              blue: 100%
              duration: 3500ms

  # - platform: monochromatic
  #   name: "LED Red"
  #   output: output_pin5

  # - platform: monochromatic
  #   name: "LED Green"
  #   output: output_pin1

# status_led:
#   pin:
#     number: 1
#     inverted: True