esphome:
  name: eh_patio
  platform: ESP8266
  board: nodemcu
  includes:
    - arduino_port_expander.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

ota:

api:

i2c:
  id: i2ccomponent

logger:
  level: DEBUG

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExpander(i2ccomponent, 0x08);
      return {ape_component};

output:
  - platform: custom
    type: binary
    lambda: |-
      return {ape_binary_output(ape, 7),
              ape_binary_output(ape, 6),
              ape_binary_output(ape, 5),
              ape_binary_output(ape, 4),
              ape_binary_output(ape, 13)};
    outputs:
      - id: gpio_relay_1
        inverted: true
      - id: gpio_relay_2
        inverted: true
      - id: gpio_relay_3
        inverted: true
      - id: gpio_relay_4
        inverted: true
      - id: ardu_13_npn

light:
  - platform: binary
    id: galeria
    name: "Galeria"
    output: gpio_relay_1
  - platform: binary
    id: patio_proyector_este
    name: "Patio Proyector Este"
    output: gpio_relay_2
  - platform: binary
    id: patio_proyector_oeste
    name: "Patio Proyector Oeste"
    output: gpio_relay_3
  - platform: binary
    id: sirena_led
    name: "LED Sirena"
    output: ardu_13_npn
    effects:
      - strobe:
      - strobe:
          name: Flash
          colors:
            - state: True
              brightness: 100%
              duration: 500ms
            - state: False
              duration: 250ms

remote_transmitter:
  pin: GPIO12
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%

switch:
  - platform: output
    id: sirena
    name: "Sirena"
    output: gpio_relay_4
  - platform: restart
    name: "Patio Restart"

  - platform: template
    id: C3_Lock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011010100001100"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C3_UnLock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011010100110000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C3_Bajar
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011010100000011"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C3_Subir
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011010111000000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms

  - platform: template
    id: C4_Lock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110111010100001100001100"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C4_UnLock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110111010100001100110000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C4_Bajar
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110111010100001111000000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C4_Subir
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110111010100001100000011"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms

  - platform: template
    id: C9_Lock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011110100001100"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C9_UnLock
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011110100110000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C9_Bajar
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011110100000011"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms
  - platform: template
    id: C9_Subir
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "110100000011110111000000"
          protocol: 1
          repeat:
            times: 5
            wait_time: 2ms

  - platform: template
    name: Comando Activacion Cerco
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "1011110110111101111000100101"
          protocol: 6
          repeat:
            times: 2
            wait_time: 2ms

cover:
  - platform: time_based
    device_class: shutter
    name: "Cortina 9 Muro"
    open_action:
      - switch.turn_on: C9_Subir
    open_duration: 40s
    close_action:
      - switch.turn_on: C9_Bajar
    close_duration: 40s
    stop_action:
      - switch.turn_on: C9_UnLock
    has_built_in_endstop: true
    assumed_state: false

  - platform: time_based
    device_class: shutter
    name: "Cortina 4 Centro"
    open_action:
      - switch.turn_on: C4_Subir
    open_duration: 40s
    close_action:
      - switch.turn_on: C4_Bajar
    close_duration: 40s
    stop_action:
      - switch.turn_on: C4_UnLock
    has_built_in_endstop: true

  - platform: time_based
    device_class: shutter
    name: "Cortina 3 Pasillo"
    open_action:
      - switch.turn_on: C3_Subir
    open_duration: 40s
    close_action:
      - switch.turn_on: C3_Bajar
    close_duration: 40s
    stop_action:
      - switch.turn_on: C3_UnLock
    has_built_in_endstop: true

binary_sensor:
  - platform: status
    name: "Patio Status"

  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 8),
              ape_binary_sensor(ape, 9),
              ape_binary_sensor(ape, 10),
              ape_binary_sensor(ape, 0),
              ape_binary_sensor(ape, 14 + 1),
              ape_binary_sensor(ape, 12),
              ape_binary_sensor(ape, 11)};

    binary_sensors:
      - name: "Puerta Frente"
        device_class: door
      - name: "Puerta Cocina"
        device_class: door
      - name: "Puerta Estudio"
        device_class: door
      - name: "Movimiento Galeria"
        device_class: motion
      - name: "Switch Galeria 1"
        internal: true
        on_state:
          then:
            - light.toggle: galeria
      - name: "Switch Galeria Proyectores"
        on_state:
          then:
            - script.execute: toggle_proyectores
        internal: true
      - name: "Switch Galeria Patio"

script:
  - id: toggle_proyectores
    then:
      - light.toggle: patio_proyector_este
      - lambda: |-
          bool esteStatus;
          id(patio_proyector_este)->current_values_as_binary(&esteStatus);
          if (esteStatus)
          {
            ESP_LOGD("main", "Este switch %d, turning on", esteStatus);
            id(patio_proyector_oeste).turn_on().perform();
          }
          else
          {
            ESP_LOGD("main", "Este switch %d, turning off", esteStatus);
            id(patio_proyector_oeste).turn_off().perform();
          }

dallas:
  pin: GPIO14
  update_interval: 600s

sensor:
  - platform: dallas
    address: 0x2771C02712646128
    name: Temperatura Patio
###
# module info:
# Male Header:
# DI3   |  DI4  |  DI8 | T13   |  5V
# 12V   |  NC   |  NC  | GND   |  A0

# Female Header
# GND  |  3.3V
# DI9  |  DI10
# A1   |  DI11
# DI12 |  NC

