esphome:
  name: eh-piscina
  platform: ESP32
  board: nodemcu-32s
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

logger:

api:

ota:
# ethernet:
#   type: LAN8720
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   clk_mode: GPIO0_IN
#   phy_addr: 1
#   power_pin: GPIO17
#   #enable_mdns: true

sensor:
  - platform: uptime
    name: Piscina uptime
  - platform: wifi_signal
    name: Piscina Wifi Signal

status_led:
  pin: GPIO12

output:
  - platform: gpio
    pin: GPIO4
    id: relay2
    inverted: true
  - platform: gpio
    pin: GPIO2
    id: relay3
    inverted: true

switch:
  - platform: gpio
    id: switch_pool_pump
    name: Bomba Piscina
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO5
      inverted: true
    on_turn_on:
      # auto turn off after 3 hours
      - delay: 3h
      - switch.turn_off: switch_pool_pump

  - platform: gpio
    name: Piscina relay 4
    pin:
      number: GPIO15
      inverted: true

light:
  - platform: binary
    name: Luz fondo este
    output: relay2
  - platform: binary
    name: Luz fondo oeste
    output: relay3
