
esphome:
  name: eh_remote_receiver
  platform: ESP8266
  board: nodemcu
  # ...

logger:

# Example configuration entry
remote_receiver:
  pin: D4
  dump: all

binary_sensor:
  - platform: remote_receiver
    name: "Panasonic Remote Input"
    nec:
      address: 0x0
      command: 0x47