esphome:
  name: test_esp8266
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

logger:
  level: DEBUG

api:

output:
  - platform: esp8266_pwm
    pin: D5
    frequency: 200 Hz
    inverted: false
    id: brightness_middle
  - platform: gpio
    pin:
      number: GPIO2
      inverted: yes
    id: led_d2

light:
  - platform: monochromatic
    output: brightness_middle
    default_transition_length: 5s
    name: "Brightness Middle"
    on_turn_on:
      then:
        - logger.log: "mono on event"
    on_turn_off:
      then:
        - logger.log: "mono off event"

  - platform: binary
    output: led_d2
    name: "binary light"
    on_turn_on:
      then:
        - logger.log: "binary on event"
    on_turn_off:
      then:
        - logger.log: "binary off event"
