esphome:
  name: test_esp8266
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600

  on_boot:
    logger.log: "hello"

packages:
  wifi: !include ../package.wifi.yaml

logger:
  level: VERBOSE

api:

ota:
