esphome:
  name: test_esp8266
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600

packages:
  wifi: !include package.wifi.yaml

logger:
  level: VERBOSE

api:

ota:

web_server:
  js_url: "https://deploy-preview-542--esphome.netlify.com/_static/webserver-v1.js"


binary_sensor:
  - platform: gpio
    pin: GPIO0
    id: la_x
    on_press:
      - logger.log: 'this is a log message telling that the gpio0 was pressed'

switch:
  - platform: template
    name: Test_SW1
    optimistic: true
  - platform: template
    name: Test_SW2
    optimistic: true
  - platform: template
    name: Test_SW3
    optimistic: true
  - platform: template
    name: Test_SW4
    optimistic: true
  - platform: template
    name: Test_SW5
    optimistic: true
  - platform: template
    name: Test_SW6
    optimistic: true
  - platform: template
    name: Test_SW7
    optimistic: true
  - platform: template
    name: Test_SW8
    optimistic: true

  - platform: template
    name: Test_SW9
    optimistic: true

  - platform: template
    name: Test_SW10
    optimistic: true

  - platform: template
    name: Test_SW11
    optimistic: true

  - platform: template
    name: Test_SW12
    optimistic: true

  - platform: template
    name: Test_SW13
    optimistic: true

  - platform: template
    name: Test_SW14
    optimistic: true
