esphome:
  name: test_esp8266
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

logger:

spi:
  clk_pin: D0
  mosi_pin: D1

api:

ota:

# Example configuration entry
mcp3008:
  cs_pin: D8

# Example config of sensors.
# This is a NTCB3950 10K thermocoupler attached to pin 0
# of the MCP3008 with a 10K resistor as a voltage divider.
# See `resistance` and `ntc` platorms for other options
sensor:
  - platform: mcp3008             # Attached to pin 0 of the MCP3008.
                                  # The result will be a reading from 0-1023
    update_interval: 1s
    id: freezer_temp_source
    number: 0                     # pin number
  - platform: resistance
    id: freezer_resistance_sensor
    sensor: freezer_temp_source
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Resistance Sensor
  - platform: ntc
    id: freezer_temp
    sensor: freezer_resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: Freezer Temperature