esphome:
  name: test_esp8266
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

logger:

api:

ota:

remote_transmitter:
  pin: GPIO0
  carrier_duty_percent: 50%

switch:
  - platform: gpio
    id: x
    pin: GPIO0
    restore_source: none
    restore_initial_value: true

climate:
  - platform: coolix
    id: cx
    restore_source: flash
    restore_initial_value:
      mode: 'off'

cover:
  - platform: template
    id: x_cover
    restore_source: none
    restore_initial_value: open

globals:
  - id: xx
    type: int
    restore_initial_value: '234'
