esphome:
  name: test_esp8266
  platform: ESP8266
  board: nodemcuv2
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

logger:
  level: VERY_VERBOSE

ota:

api:

colors:
  - id: kbx_red
    red: 100%
    green: 1%
    blue: 5%

spi:
  mosi_pin: GPIO4
  miso_pin: GPIO5
  clk_pin: GPIO4

font:
  - id: helvetica_small
    file: pixelmix.ttf

display:
  - platform: st7789v
    id: main_lcd
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO4
    rotation: 270
    pages:
      - id: page1
        lambda: |-
          it.print(235, 5, id(helvetica_small), id(kbx_red), TextAlign::TOP_RIGHT, "Offline");
          // ...or use a predefined color from 'color.h' like this:
          it.print(235, 5, id(helvetica_small), esphome::COLOR_GREEN, TextAlign::TOP_RIGHT, "Online");
