esphome:
  name: test-esp8266
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

logger:

api:

ota:

i2c:

sensor:
  - platform: bh1750
    name: lele

external_components:
  #- source: github://esphome/esphome@importlib-custom-components

  - source:
      type: local
      path: components
    components: [bh1750]
